---
layout: blog
title: Bleeding edge on Docker
permalink: /blog/:year/:month/:day/bleeding-edge-on-docker
date: '2016-07-20T01:21:00.000-07:00'
author: slaskawiec
tags: [ " docker" ]
---
As you may have noticed our
https://hub.docker.com/r/jboss/infinispan-server[Docker images] are
published together with (or very soon after) releases. But what if you
want to try out some brand features which have just been merged? In that
case you need to build an image by yourself.


== Step #1 - Clone JBoss Docker image repository



At first, you will need to clone our Infinispan Docker images:

== 

== Step #2 - Build or download the latest SNAPSHOT



There are two options here - you can build the distribution yourself or
use SNAPSHOTs available on
https://repository.jboss.org/nexus/content/repositories/snapshots/org/infinispan/[JBoss
Nexus repository].



The first option requires checking out the Infinispan source code and
performing a Maven build:


The second one is much simpler (Infinispan SNAPSHOTs are pushed into the
repository after each successful build:

==

== Step #3 - building Infinispan Docker image



One of the steps for building Infinispan Docker image is to download the
distribution from  https://infinispan.org/download/[Infinispan Download]
page. We need to slightly modify this step and use our manually
downloaded packages.



Modify the Dockerfile as shown below:

Now you are ready to invoke the Docker build:



== Conclusion



As you can see building a SNAPSHOT based docker image is very simple.
From my own experience I can tell you that pushing it into Docker Hub is
the fastest way to start playing with it in any PaaS environment (e.g.
https://www.openshift.com/devpreview/register.html[Openshift Online])

Happy building!




