---
layout: blog
title: Infinispan joins Commonhaus Foundation
permalink: /blog/:year/:month/:day/commonhaus-foundation
date: '2025-01-13T00:00:00.000-00:00'
author: ttarrant
tags: [ "foundation" ]
---

= Infinispan joins Commonhaus!

We’re very excited to announce that Infinispan is https://www.commonhaus.org/activity/223.html[joining the Commonhaus Foundation].

== Why join a foundation?

We want to make it clear that Infinispan's roadmap is independent of the company that has funded its development since day 1,
and we welcome contributors to participate in what we think is a bright future for our project. In the same vein, we've also recently
https://infinispan.org/blog/2024/11/29/github-issues[transitioned our issue tracking] to a neutral platform.

== Why Commonhaus?

Commonhaus just ticks all the right boxes for us: its lightweight governance is ideal. We get all the benefits of being
part of an awesome foundation, with all the benefits of running the project on our own terms.

Commonhaus is also the home to a number of "friend projects": Hibernate, Quarkus, Debezium, Jackson all play a key role
in our software and it's great that we share a "common home".

