---
layout: blog
title: "Infinispan Operator 2.4.0"
permalink: /blog/:year/:month/:day/infinispan-resp-resque-use-case
date: '2024-03-20T00:00:00.000-00:00'
author: remerson
tags: [ "release", "operator", "kubernetes"]
---

= Infinispan Operator 2.4.0

We're pleased to announce
https://operatorhub.io/operator/infinispan/stable/infinispan-operator.v2.4.0[version 2.4.0 of the Infinispan Operator]
for Kubernetes and Red Hat OpenShift.

This is the first Operator release based on Infinispan 15.

== Release highlights:

* Infinispan 14.0.27.Final support
* Infinispan 15.0.0.Final support
* Allow Readiness, Liveness and Startup probe values to be configured
* Simplify JGroups configuration to use "Kubernetes" stack provided by Infinispan server
* CloudEvents integration no longer has any effect with 15.0.x servers onwards
* Cross-Site Replication (XSite) improvements:
** Use TLSv1.3 as default
** TLS client authentication by default
** Configure Gossip Route idle connection timeout

== OperatorHub Channel

From this release onwards all Infinispan Operator releases will be added to the "stable" channel. Please transition from
the "2.3.x" Subscription channel to "stable" in order to consume 2.4.0.

Our intention is to continue our current versioning scheme, whereby the Operator minor version is incremented when support
for a new Infinispan major version is added. However, to simplify upgrades, all future Operator releases will be added to
the "stable" channel, instead of `x.y.z`, so that it's no longer necessary for the Subscription channel to be changed when
upgrading.

== Infinispan Server Support

Future 2.4.x Operator releases will include the latest releases for both the 15.0.x and 14.0.x Infinispan server streams.
While we always recommend users to transition to the latest Infinispan major version as soon as possible, supporting both
server streams in the Operator will provided additional flexibility those depending on Infinispan as part of a 3rd party
integration, e.g. Keycloak users.
