---
layout: blog
title: "Infinispan RESP in action: Resque use case"
permalink: /blog/:year/:month/:day/infinispan-resp-resque-use-case
date: '2024-01-19T00:00:00.000-00:00'
author: rigazilla
tags: [ "demo", "use case", "resp", "redis"]
---

= Infinispan RESP in action: Resque use case

As you may know Infinispan 15 extended its RESP compatibility implementing most of the command related to the principal data types (set, list, hashes, sorted set...).

In this post we want to present a demo case of integration between a real application (https://github.com/resque/resque[Resque]) and Infinispan used as a Redis-compatible cache backend. +
Aim of this is to show how it's easy to switch between Redis and Infinispan making available to your application all the advanced features of our clustered cache server.

Resque is a job scheduler that creates jobs and send them to execution queues, it uses Redis as default backend and provides a testsuite and a demo application. +
Try yourself how Infinispan can seamlessly replace the default backend: just clone
https://github.com/rigazilla/resque/tree/ispn-testsuite[this Resque fork] and follow the https://github.com/rigazilla/resque/blob/ispn-testsuite/README.ispn.md[Infinispan README] to run both the test suite and the demo application.

Everything worked as a charm? Nice! Now check the diff with the original project, we only added code to turn on/off Infinispan instead of Redis. Nothing more than that! (*)

Hope you ejoyed this post!

Cheers, +
The Infinispan Team

(*) What? You also noticed we changed the expected result for a test. Surely you can easily guess why... if not just ask us on https://infinispan.zulipchat.com/#[Zulip]!