---
layout: blog
title: 'More on transaction performance: use1PcForAutoCommitTransactions'
date: '2011-11-23T08:21:00.000-08:00'
author: Mircea Markus
tags: [ "transactions",
"performance",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-8720447815938181630
blogger_orig_url: https://blog.infinispan.org/2011/11/more-on-transaction-performance.html
---
== What's _use1PcForAutoCommitTransactions_ all about?



Don't be scared the name, _use1PcForAutoCommitTransactions_ is a new
feature (5.1.CR1) that does quite a cool thing: increases your
transactions's performance.
Let me explain.
Before Infinispan 5.1 you could access the cache both transactional and
non-transactional. Naturally the non-transactional access is faster and
offers less consistency guarantees.But we don't support mixed access in
Infinispan 5.1, so what what's to be done when you need the speed of
non-transactional access and you are ready to trade some consistency
guarantees for it?
Well here is where _use1PcForAutoCommitTransactions_ helps you. What is
does is forces an induced (_autoCommit=true_) transaction to commit in a
single phase. So only 1 RPC instead of 2RPCs as in the case of a full 2
Phase Commit (2PC).


== At what cost?


You might end up with inconsistent data if multiple transactions modify
the same key concurrently. But if you know that's not the case, or you
can live with it then _use1PcForAutoCommitTransactions_ will help your
performance considerably.


== An example


Let's say you do a simple put operation outside the scope of a
transaction:



Now let's see how this would behave if the cache has several different
transaction configurations:

=== Not using 1PC...




The put will happen in two RPCs/steps: a prepare message is sent around
and then a commit.


=== Using 1PC...




The put happens in one RPC as the prepare and the commit are merged.
Better performance.


=== Not using autoCommit




An exception is thrown, as this is a transactional cache and invocations
must happen within the scope of a transaction.

Enjoy!
Mircea
