---
layout: blog
title: HotRod client in OSGi
date: '2014-03-06T03:13:00.001-08:00'
author: Martin Genčúr
tags: [ "hotrod",
"osgi",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1217573772983209054
blogger_orig_url: https://blog.infinispan.org/2014/03/hotrod-client-in-osgi.html
---
Infinispan 7.0.0.Alpha1 makes it possible to easily run the HotRod
client in an OSGi based container such as Karaf. Until this point there
was no easy way to find out which libraries were required for the HotRod
client to run in OSGi. These libraries then had to be installed manually
and dynamic imports enabled for all the libraries. Last but not least,
it was not possible to use the latest HotRod feature - remote queries.

The 7.0.0.Alpha1 introduces a "features" file which not only lists all
dependencies required for correct functionality of the HotRod client in
OSGi, but also makes it very easy to install the whole feature into
Karaf (version 2.3.3 or 3.0) in just a few steps.


== HotRod client feature file for OSGi

The feature file has been deployed into JBoss Nexus repository so it's
publicly available. It looks like this:



== Installing the HotRod client feature in Karaf

The HotRod feature (either a simple HotRod client or HotRod client with
remote query capabilities) can be installed in Karaf in the following
steps:



There's still one limitation with respect to remote querying, though.
The remote query feauture requires a JMX-based connection to Infinispan
server in order to be able to register a .protobin file, which holds the
description of data types being transferred between the client and
server. Since a remoting-jmx protocol is required and the existing
remoting-jmx client does not work correctly in OSGi (see
https://issues.jboss.org/browse/ISPN-4011), it is required to register
the .protobin file in another way - not from inside the OSGi container.
This will be fixed in one of the next releases.



Stay connected for news about running the whole Infinispan datagrid in
OSGi, not only the HotRod client. This is work in progress.



Cheers,

Martin
