---
layout: blog
title: Cache and Cache Manger events in CDI
date: '2014-09-25T07:05:00.000-07:00'
author: Sebastian Łaskawiec
tags: [ "event",
"cdi",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1353786930345003069
blogger_orig_url: https://blog.infinispan.org/2014/09/cache-and-cache-manger-events-in-cdi.html
---
A long time ago, in a coffee bar far, far away,
http://blog.infinispan.org/2011/09/when-infinispan-meets-cdi.html[Infinispan
met CDI.] The two had the most amazing espressos, but they noticed that
service was not as efficient as they wished. To help them out, the CDI
support has been extended to include CDI Events.


== Coffee Events



In case you haven't heard about CDI events, here is a really quick
example:


When _Waiter_ receives an order - he fires a CDI event. On the other
hand _Barista_ acts as a listener for ordered coffees (_@CoffeeOrdered_
and _@Observes_). As a result _Barista_ and _Waiter_ are loosely coupled
and moreover they don't know anything about each other.


== Cache based Coffee Events



Now let's complicate this situation a little bit... Let's assume that
when Waiter is passing an order to Barista, he might be actually busy
processing another order. So let's introduce a little buffer between
them - Waiter puts an order into the Cache and later on - Barista takes
it and prepares our delicious coffee...




== Beyond good espressos


As you can see - introducing CDI improved the service a lot. Now
_Waiter_ does not hurry _Barista_ with the orders. This is why they
serve the best espresso in the world there...

They have also a lot more time to think about other improvements (and to
be honest... I think they will
introduce __CacheEntryModifiedEvent, CacheEntryRemovedEvent
and CacheStartedEvent __really shortly)... Or perhaps they'll find some
other ideas in
http://infinispan.org/docs/7.0.x/user_guide/user_guide.html#_listeners_and_notifications[Infinispan's
manual]?
