---
layout: blog
title: 
date: '2014-10-06T03:44:00.000-07:00'
author: Gustavo
tags: [ "judcon",
"lucene",
"cep",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-8118758295288640020
blogger_orig_url: https://blog.infinispan.org/2014/10/judcon-brazil-2014-second-edition-of.html
---
=== [.underline]#
Judcon Brazil 2014#



The second edition of Judcon Brazil was held in São Paulo on September
26th, this time in a single day.

Considering the proximity of JavaOne, we had many top quality speakers
presenting to a packed house attending the 4 tracks dedicated to Cloud,
NoSQL/Data, Rule Process & Integration and 'Cool Stuff'.



The talks were delivery both in English and Portuguese (with
simultaneous translations) by well known Jboss community members and
leaders. I had the privilege to present
"http://www.slideshare.net/gustavonalle/judcon-brazil-2014-lucene-from-bottom-up?qid=116b8a4f-b728-4fde-8c71-46b68ceb4a54&v=qf1&b=&from_search=1[Lucene
from the bottom up]" and received many positive feedbacks after the
talk, when I had the opportunity to discuss about Lucene usage inside
and outside Infinispan.

I also took the chance to see "Real Time Complex Event Monitoring"
delivered by Guna Vijayaratnam showing how to leverage Infinispan in a
complex event processing system with real time visualization, a really
interesting use case of the Data Grid.



Overall the conference had a flawless organization with cool technical
content, plus a nice venue surrounded by amazing gastronomical offers
(picanha anyone?). Combined with the traditional Brazilian hospitality,
Judcon Brazil 2014 was a great success, hope to attend again next year !


