---
layout: blog
title: Infinispan 7.2.3.Final
date: '2015-06-19T08:34:00.004-07:00'
author: Tristan Tarrant
tags: [ "bugfix",
"release",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1090510311518587084
blogger_orig_url: https://blog.infinispan.org/2015/06/infinispan-723final.html
---
Dear Infinispan users,

thanks to your help, a few bugs have been found and fixed in the
Infinispan 7.2 branch. So if you are affected by any of the bugs below,
now is the time to upgrade.


== Bug

* [https://issues.jboss.org/browse/ISPN-4123[ISPN-4123]] - Remote Query
tests random failures
* [https://issues.jboss.org/browse/ISPN-5444[ISPN-5444]] -
Filter/converters in server can't unmarshall custom cached classes
* [https://issues.jboss.org/browse/ISPN-5522[ISPN-5522]] - LIRS
BoundedConcurrentHashMapv8 eviction for tree bin missing check
* [https://issues.jboss.org/browse/ISPN-5524[ISPN-5524]] - Race
condition in SemaphoreCompletionService.executeFront()
* [https://issues.jboss.org/browse/ISPN-5527[ISPN-5527]] - Java system
properties no longer supported in leveldb expiration path
* [https://issues.jboss.org/browse/ISPN-5531[ISPN-5531]] -
java.lang.UnsupportedOperationException during remove (using
RemoteCacheManager)
* [https://issues.jboss.org/browse/ISPN-5543[ISPN-5543]] - Bad tracef
arguments are causing IllegalFormatConversionException
* [https://issues.jboss.org/browse/ISPN-5560[ISPN-5560]] -
NotSerializableException for invalidation-cache
* [https://issues.jboss.org/browse/ISPN-5565[ISPN-5565]] - Memory leak
in Hot Rod client tests
* [https://issues.jboss.org/browse/ISPN-5566[ISPN-5566]] - Listener
Observation is not obeyed for non CacheEntryEvents

== Enhancement

* [https://issues.jboss.org/browse/ISPN-5519[ISPN-5519]] - Cannot choose
to run index-less query on an indexed cache in compat mode 

Again, http://infinispan.org/download/[downloads] and
http://infinispan.org/release-notes/[release notes] are at the usual
pages, so go and check them out !

Happy hacking.




