---
layout: blog
title: The return of the Cassandra CacheStore
date: '2016-02-03T02:10:00.002-08:00'
author: Tristan Tarrant
tags: [ "persistence",
"cassandra",
"cache store",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-3387044271722101906
blogger_orig_url: https://blog.infinispan.org/2016/02/the-return-of-cassandra-cachestore.html
---
Ever since we spruced up our Cache Store SPI in Infinispan 6.0, some of
our "extra" cache stores have lied in a state of semi-abandonment,
waiting for a kind soul with time and determination to bring them back
to life.
I'm glad to announce that such a kind soul, in the form of Jakub Markos,
had the necessary qualities to accomplish the resurrection of the
Cassandra Cache Store.

http://cassandra.apache.org/[Apache Cassandra] is a database with a
distributed architecture which can be used to provide a virtually
unlimited, horizontally scalable persistent store for Infinispan's
caches. The new Cassandra Cache Store leverages the Datastax Cassandra
client driver instead of the old Thrift client approach, which makes it
much more robust and reliable.

== Configuration

In order to use this cache store you need to add the following
dependency to your project:

You will also need to create an appropriate keyspace on your Cassandra
database, or configure the auto-create-keyspace to create it
automatically.
The following CQL commands show how to configure the keyspace manually
(using cqlsh for example):




You then need to add an appropriate cache declaration to your
`infinispan.xml`
(or whichever file you use to configure Infinispan):


It is important the the shared property on the cassandra-store element
is set to true
because all the Infinispan nodes will share the same Cassandra
cluster.


== Limitations

The cache store uses Cassandra's own expiration mechanisms (time to live
= TTL) to handle expiration of entries. Since TTL is specified in
seconds, expiration lifespan and maxIdle values are handled only with
seconds-precision.

In addition to this, when both lifespan and maxIdle are used, entries in
the cache store effectively behave as if their lifespan = maxIdle, due
to an existing bug https://issues.jboss.org/browse/ISPN-3202.

So, try it out and https://developer.jboss.org/en/infinispan/content[let
us know] about your experience !


