---
layout: blog
title: Microservices with Wildfly Swarm and Infinispan
date: '2016-10-11T00:20:00.001-07:00'
author: Sebastian Łaskawiec
tags: []
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-6101441236279944854
blogger_orig_url: https://blog.infinispan.org/2016/10/microservices-with-wildfly-swarm-and.html
---
Everybody loves Microservices, right?

Today, all of us have slightly different understanding what
Microservices are but, among all those definitions and attributes,
there's probably one thing that fits them all - they need to be
[.underline]#simple#.

So let's have a look at some practical example of creating a REST
service with Infinispan as a storage wired together using CDI. We will
use http://wildfly-swarm.io/[Wildfly Swarm] as a running platform.


== Bootstrapping new project



A good way to start a new Wildfly Swarm project is to
http://wildfly-swarm.io/generator/[generate it]. The only requirement
here is to add "JAX-RS with CDI" and "JPA" as dependencies.



The next step is to add _infinispan-embedded_ artifact. The final
_pom.xml_ should look like the following:





== Writing some code



http://infinispan.org/docs/dev/user_guide/user_guide.html#cdi_support[Infinispan
CDI Extension] will take care of bootstrapping Infinispan, so we can
dive directly into JAX-RS code:







And that's it!



== What's next?



If you'd like to have a look at the complete example, check
out https://github.com/slaskawi/infinispan-wf-swarm-example[my
repository]. The code is based on fresh build from Infinispan master
branch which contains lots of improvements for CDI. You might build it
yourself or just wait for _9.0.0.Beta1_.



Have a lot of fun with Microservices!
