---
layout: blog
title: Event Listener with C++
date: '2017-03-17T10:59:00.001-07:00'
author: rigazilla
tags: [ "c++", "example", "quick start", "remote events" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-3678330413321250526
blogger_orig_url: https://blog.infinispan.org/2017/03/event-listener-with-c.html
---
Dear Infinispan community,

as announced in a previous
http://blog.infinispan.org/2016/11/hotrod-clients-cc-810alpha2-released.html[post],
starting from version 8.1.0 also the C++/C# clients can receive and
process Infinispan events.

Here's an example of usage of C++ event listeners that, with a good dose
of imagination, pretends to be a customer behavior tracking system for
our store chain (don't take this too seriously, we're just trying to add
some fiction).

As a first requirement our tracking system will record every single
purchase made in our stores. How many stores we have? 1, 100, millions?
It doesn't matter: we're backed with an Infinispan data grid.
This is version 0.x and hence the checker must use the keyboard to enter
all the needed information.


As you can see our entry key is a concatenation of the product name and
the timestamp and the entry value is an unstructured string, maybe too
simply but it could work for now.
Seems we are at a good point: we have the data and we can do analytics
on it, so far so good but now our boss makes a new request: he wants a
runtime monitor on how's the sales performance. That's a perfect request
to be fulfilled with event listener: the monitor application will be an
Hotrod C++ client that registers a client listener on the server and
receives and show on the boss's laptop the data flow.
A client listener, once registered on the server, can receive events
related to: creation, modification, deletion, expiration of cache
entries; in our example only the creation and expiration events are
processed (expired events can be useful to do some moving average
statistics?). Following a snip of code that creates and registers a
listener that writes the events key on the stdout.


You can git this quickstart here
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#fn1[1]].
On startup a multiple choice menu is shown with all the available
operations. Running several instances you can act as the checker (data
entry) or the boss (installing the listener and seeing the events
flow).




== *Filters*

Again so far so good, but then the marketing department ask support to
do targeted advertising like: soliciting customers that bought product Y
to buy product X.
Let's suppose that X="harmonica" and Y="hiking boots" (it's a well known
fact of life that in the high mountains you feel the desire to play an
harmonica).

To do that we register on the server another listener, but this time
we're not interested in the whole flow of purchase data: to run our
marketing campaign, we only interested in cache entries having the key
starting with "hiking". The Infinispan server can filter out events for
us, if we pass in the AddClientListener operation the name of the wanted
filter along with any configuration arguments.


Filter are java classes that must be deployed into the Infinispan server
(more here
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#fn2[2]])

== *and converters*

Predefined events contain very few information: basically the event type
and the entry key, this to prevent to flood the network spreading around
very long entry values. Users can override this limitation using a
converter, that is a java class deployed into the server, that can
create custom events containing every data needed by the application.


As in the previous case, we pass into the add operation the name of the
converter and the configuration arguments, any.

That's all guys, let us know your feedback: do you like it? Could be
better? Tell us how it can be improved creating an issue
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#fn3[3]],
or fork and improve it yourself
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#fn4[4]]*!*

Thanks for reading and enjoy!
The Infinispan Team
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref1[1]]
https://github.com/rigazilla/infinispan-simple-tutorials/tree/new_event_tutorial/c%2B%2B/events
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref2[2]]
http://blog.infinispan.org/2014/08/hot-rod-remote-events-1-getting-started.html
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref2[2]]
http://blog.infinispan.org/2014/08/hot-rod-remote-events-2-filtering-events.html
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref2[2]]
http://blog.infinispan.org/2014/09/hot-rod-remote-events-3-customizing.html
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref3[3]]
https://issues.jboss.org/projects/HRCPP/issues
[https://www.blogger.com/blogger.g?blogID=5717179571414330874#ref4[4]]
https://github.com/infinispan/cpp-client
