---
layout: blog
title: Infinispan 10.1.0.CR1
permalink: /blog/:year/:month/:day/infinispan-10
date: '2019-12-09T12:00:00.000-00:00'
author: ttarrant
tags: [ "release candidate", "release" ]
---

= Infinispan 10.1.0.CR1

Dear Infinispan community,

as we are closing in on 10.1, we have been working on a lot of polishing and bugfixing.

== Server

* The new console has received a lot of improvements, 
* A new welcome page
* A command-line switch to specify an alternate logging configuration file

== Query

The query components have been reorganized so that they are more modular.

== Monitoring

* The introduction of histogram and timer metrics.

== Stores

* The REST cache store has been updated to use the v2 RESTful API.

== Removals and deprecations

* The old RESTful API (v1) has been removed
* The Infinispan Lucene Directory has been deprecated.
* The memcached protocol server has been deprecated. If you were relying on this, come and talk to us about working on a binary protocol implementation.


== Bug fixes, clean-ups and documentation

Over 40 issues fixed including a lot of documentation updates. See the link:[full list of changes and fixes]

Infinispan 10.1.0.Final is scheduled for December the 20th.

