---
layout: blog
title: Infinispan 10.0.0.Beta2 and 9.4.8
date: '2019-02-21T08:31:00.000-08:00'
author: Tristan Tarrant
tags: [ " beta", "release", "final" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-2539171124591722906
blogger_orig_url: https://blog.infinispan.org/2019/02/infinispan-1000beta2-and-948.html
---
Hello Infinispan users,

What ? You're wondering where Beta1 is ? And what happened to 9.4.7 ?
Unfortunately, those releases, while tagged and available on your
closest Maven Central mirror will only work with Java 11, so we had to
rebuild and re-release.

So, without further ado, I give you 10.0.0.Beta2 and 9.4.8.Final.

The first change I should outline is one that will impact you if you are
building Infinispan from source. The previous build structure required
having both JDK 8 and JDK 11 in order to compile a release which worked
on both. In order to simplify the build process, as well as ensuring
that the output is always consistent we now require Java 11 only. Don't
worry: the resulting binaries will still work on Java 8 and greater.


== 10.0.0.Beta2

The first beta of our next major release contains a number of
enhancements:

[https://issues.jboss.org/browse/ISPN-9847[ISPN-9847]] - Extend
configuration to allow inline JGroups configuration and inheritance
[https://issues.jboss.org/browse/ISPN-9699[ISPN-9699]] - Cluster member
owning no data
[https://issues.jboss.org/browse/ISPN-8124[ISPN-8124]] - ServerNG:
Initial implementation

We will soon be posting about these features individually.

The work on persistent storage long-term compatibility is progressing
with
[https://issues.jboss.org/browse/ISPN-9845[ISPN-9845]] - Stop exposing
InternalMetadata via the persistence SPI

Notable fixes:

[https://issues.jboss.org/browse/ISPN-4075[ISPN-4075]] - State transfer
should preserve the creation timestamp of entries

And if you were still using the old Distributed Executor, that has been
finally removed in
[https://issues.jboss.org/browse/ISPN-9784[ISPN-9784]] - Remove
Distributed Executor


== 9.4.8.Final

Our latest point release contains lots of bug fixes and minor
enhancements.

As usual you can ask questions on the
https://developer.jboss.org/en/infinispan/content[forum],
https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow]
and interactively on our http://infinispan.zulipchat.com/[Zulip Chat].
Please report any bugs you find on our
https://issues.jboss.org/projects/ISPN/summary[Issue Tracker]
