---
layout: blog
title: Infinispan Spring Boot Starter 2.1.5.Final and 1.0.7.Final are out!
date: '2019-04-05T02:48:00.003-07:00'
author: Katia Aresti
tags: [ "release", "spring boot" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-6961437587141942321
blogger_orig_url: https://blog.infinispan.org/2019/04/infinispan-spring-boot-starter-215final.html
---

Dear Infinispan and Spring Boot users,

We have just
released https://github.com/infinispan/infinispan-spring-boot[Infinispan
Spring Boot Starter] **2.1.5.Final **and *1.0.7.Final*.


==== *2.1.5.Final*

*
* **2.1.5.Final** is using** Infinispan 9.4.11.Final** and **Spring-Boot
2.1.4.RELEASE**.

===== *Important Spring-Boot bug fix*

Previous versions of Spring-Boot 2.1.x contained a bug related to the
https://openjdk.java.net/jeps/238[multi-release jars]. Infinispan
contains multi-release jars, in consequence, we could not run our
applications using java -jar with Java 11 (Java 8 worked fine). For
additional explanations, read
https://stackoverflow.com/questions/54635814/why-does-infinispan-fail-with-noclassdeffounderror-on-spring-boot-java-11[here].
Spring-Boot team has fixed
this https://github.com/spring-projects/spring-boot/issues/15981[bug] and
released the correction in Spring-Boot 2.1.4.RELEASE, along with
https://github.com/spring-projects/spring-boot/releases/tag/v2.1.4.RELEASE[many
other features and bug fixes], so consider upgrading soon.

===== *Statistics on Client/Server mode and Actuator*

Statistics configuration in client/server mode for the client evolved in
the latest Infinispan versions. As a remainder, to activate actuator
statistics in client/server mode :
"Configure 'infinispan.remote.statistics=true' in the",
*application.properties*
[.underline]#or#
- Configure ''infinispan.client.hotrod.statistics=true" in the
*hotrod-client.properties*
[.underline]#or#
- Configure by code, for example:

@Bean
public InfinispanRemoteConfigurer infinispanRemoteConfigurer() \{
    return () -> new
ConfigurationBuilder().statistics().enable().build();
}

===== 

===== JMX

If you want to use Infinispan and JMX, for example on Client/Server
mode, set the 'jmx' property 'true' as explained above with the
'statistics' property. However, you might get
a javax.management.InstanceAlreadyExistsException because both
Infinispan and Spring will try to register the MXBean.

The correction will land on the next starter release. If you need to
avoid this error today, you can tell Spring-Boot not to register the
bean with the following code (Thanks Stéphane Nicoll for the tip!):




===== 

===== Testcontainers

This version includes an integration test using
https://testcontainers.org/[Testcontainers],
https://junit.org/junit5/[JUnit5] and the
https://hub.docker.com/r/jboss/infinispan-server[Infinispan Server].
Grab a look
https://github.com/infinispan/infinispan-spring-boot/blob/90e79a81dd32a6c9462e76bfdfb175e2c751b3f0/infinispan-spring-boot-starter-remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java[here] if
you are curious.



==== *1.0.7.Final*

*
* *1.0.7.Final* upgrades to *1.5.19.RELEASE* and Infinispan
*9.4.11.Final*.


⭐ Don't forget to *star* the project in
https://github.com/infinispan/infinispan-spring-boot[GitHub] if you like
the starter! ⭐



You can find these releases in the maven central repository.

Please report any issues in
our https://issues.jboss.org/projects/ISPN[issue tracker] and join the
conversation in our https://infinispan.zulipchat.com/[Zulip Chat] to
shape up our next release.

Enjoy,

The Infinispan Team
