---
layout: blog
title: Operator 0.2.1 out with DNS ping and expanded customizations
date: '2019-04-08T01:00:00.000-07:00'
author: Galder Zamarreño
tags: [ " release", "openshift", "operator", "beta release" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-8098395875181504341
blogger_orig_url: https://blog.infinispan.org/2019/04/operator-021-out-with-dns-ping-and.html
---
We've just completed the release of the Infinispan Operator version
0.2.1. In this second minor release, we've added the following
features:


==== DNS Cluster Discovery


Cluster nodes now discover each other using DNS ping, which uses name
lookups. Each node publishes a headless service which they use to locate
each other. Previously, Kubernetes APIs were queried to discover other
nodes, but this required administrator rights. DNS ping does not require
admin permissions.


==== Configurable Image


The Infinispan server image used by the operator is now configurable,
e.g.

==== Configurable XML


You can now provide their own custom Infinispan server XML referencing
an existing ConfigMap:


Note that this example requires a ConfigMap with the XML file to be
created before hand.


==== Next Steps


We're already working on version 0.3.0, and in parallel we've been
working on our first OperatorHub submission. We hope to have some news
for you very soon :)

Cheers,
Galder

