---
layout: blog
title: Infinispan Operator 1.1.1 is out!
date: '2020-02-24T12:00:00.000-00:00'
author: Vittorio Rigamonti
tags: [ "release", "operator" ]
---

We're pleased to announce
https://operatorhub.io/operator/infinispan[version 1.1.1 of the Infinispan Operator]
for Kubernetes and OpenShift.

This release has focused on fixing bugs and improving robustness, mainly related to the following:

- improving reconcile flow stability
- reducing Operator CPU load
- cleaning up logs

Our community documentation on https://infinispan.org/documentation has also been updated and improved. You can find some of the 
changes at:

- https://infinispan.org/infinispan-operator/master/operator.html#creating_services[Creating Infinispan Services]
- https://infinispan.org/infinispan-operator/master/operator.html#network_services[Setting Up Network Services] 
- https://infinispan.org/infinispan-operator/master/operator.html#prometheus[Monitoring Infinispan with Prometheus]
- https://infinispan.org/infinispan-operator/master/operator.html#remote_connections[Connecting to Infinispan Clusters]

== Automatic Upgrades
If you installed the Infinispan Operator on Red Hat OpenShift with the Automatic Approval upgrade policy, 
your cluster should already be running the latest versions (Infinispan Operator 1.1.1 with Infinispan 10.1.2.Final).

We would like to hear opinions from you about the automated upgrade process, so get in touch if you
have any issues or want to give any feedback.

== Get it, Use it, Ask us!

Try the
https://github.com/infinispan/infinispan-simple-tutorials/tree/master/operator[simple tutorial]
for the Operator, which has been updated for this version.

You can https://github.com/infinispan/infinispan-operator/issues[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

Finally, a detailed list of issues and features for this version can be found
https://github.com/infinispan/infinispan-operator/issues?q=milestone%3A1.1.1+is%3Aclosed[here].
