---
layout: blog
title: Infinispan 11.0.0.CR1
date: '2020-05-25T12:00:00.000-00:00'
author: Tristan Tarrant
tags: [ "release" ]
---

= Infinispan 11.0.0.CR1

Dear Infinispan community,

we've just released 11.0.0.CR1 which comes loaded with quite a few features and improvements.

== Cross-Site Replication Improvements

The cross-site replication feature received two major improvements:

* Support for multiple site masters
+
The new algorithm is able to take advantage of multiple site masters, distributing load between them. If your environment is capable, increase the number of site masters in RELAY2 configuration:
+
[source,xml]
----
<relay.RELAY2 site="LON" max_site_masters="1000"/>
----
+
* Conflict detection and resolution for Asynchronous Cross-Site Replication
+
Taking advantage of vector clocks, in asynchronous mode, Infinispan is able to detect conflicts. 
A conflict happens when 2 or more sites update the same key at the same time.
Conflicts are resolved based on the site's names. Updates from the site lexicographically lower, take priority, in case of  conflicts.
As an example, if you have 3 sites, LON, NYC and SFO, conflicts between LON and NYC discards updates from NYC and keeps the updates from LON. 
You can choose the priority by prepending a number to the site name. For example, if you want updates from NYC to take priority, you can set the site name to “1-NYC”.

In a future update, Infinispan will allow you to set a custom conflict resolution algorithm.

== Non-blocking internals
* All thread pools collapsed into two pools: blocking and non-blocking

== Persistence
* A new non-blocking Store SPI

== Clustering
* More accurate segment rebalancing
* Scaling without state-transfer (experimental)

== Query/Indexing
* SearchManager, CacheQuery are deprecated. Users are encouraged to migrate to Ickle String queries obtained from Search.getQueryFactory

== Server Security
* The server is now secure by default
* New encrypted properties realm
* Simplified authentication and authorization configuration to be as automatic as possible

== Other Server changes
* Datasources
* Runtime logging configuration
* Server report

== CLI
* User Tool merged into CLI
* CLI can be compiled natively
* Non-interactive usage

== Console
* Lots of UX improvements

== Kubernetes/OpenShift operator
* Cache CR
* Service .Expose with Ingress and Route

== Container images
* Images based upon ubi-minimal:8.2
* Native generation of config files in all images
* Native server image available at `infinispan/server-native` (Experimental)

== Documentation
* Added procedural content for rolling upgrades, Cache CR with the Operator, server patching, misc CLI commands, using RemoteCacheConfigurationBuilder.
* Procedural content for different upgrade and migration tasks included in Upgrade Guide.
* Operator and Spring Boot Starter guides now provide stable and development versions from the index page.
* Updated index.html and throughout documentation to improve high-level context and aid retrievability.
* Getting Started content updated and streamlined.
* Applied several modifications, additions, and removals to documentation via community feedback.

== Get it, Use it, Ask us!

Please https://infinispan.org/download/[download],
https://issues.jboss.org/projects/ISPN[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

