---
layout: blog
title: Infinispan Node.js client supports query
permalink: /blog/:year/:month/:day/infinispan-js-client
date: '2022-09-25T12:00:00.000-00:00'
author: Neeraj Gartia
tags: [ "hotrod", "Node.js", "client", "javascript", "release", "Protobuf", "query" ]
---

== Node.js Client 0.9.0

Infinispan Node.js client version 0.10.0 was released last week with added support of query with `application/x-protostream` data format.
Up until now, our Node.js client only supported `text/plain` and `application/json` data formats.

==== `application/x-protostream` data format
You can now use the `application/x-protostream` data format for all the Hot Rod operations supported in js-client. To make the Node.js client backwards compatible, the client still treats key/value pairs as String by default.

==== query
The Hot Rod js-client now also supports query method to perform queries on caches. For more information about querying infinispan caches, refer to https://infinispan.org/docs/stable/titles/query/query.html[the query documentation].

IMPORTANT: You must set the data-format as `application/x-protostream` to perform queries on your cache.

For the working code example of the query feature, please refer to https://infinispan.org/docs/hotrod-clients/js/latest/js_client.html#_working_with_queries[this].


== To go further

Full client documentation is now available in the
https://infinispan.org/docs/hotrod-clients/js/latest/js_client.html[Hot Rod JS Client Guide].

Jira tracker for this client is available https://issues.redhat.com/projects/HRJS[here].
