---
layout: blog
title: Infinispan Operator 1.1.2 is out!
date: '2020-06-08T12:00:00.000-00:00'
author: Vittorio Rigamonti
tags: [ "release", "operator" ]
---

We're pleased to announce
https://operatorhub.io/operator/infinispan[version 1.1.2 of the Infinispan Operator]
for Kubernetes and Red Hat OpenShift.

Release highlights:

- Simplified configuration for external services.
- Improved readability of CR yaml output.
- Now available from the https://quay.io/repository/infinispan/operator?tag=latest&tab=tags[Operator image registry] at quay.io.

Get full release information at https://github.com/infinispan/infinispan-operator/milestone/10?closed=1[version 1.1.2].

Our community documentation has also been updated and improved! Be sure to check out the
https://infinispan.org/infinispan-operator/1.1.x/operator.html[Infinispan Operator v1.1.x Guide].

== Update Channels and Automatic Upgrades on OpenShift
Starting with this release we are moving channels from a stable/preview structure to a micro-stream structure. This means 
you'll get channels for each major.minor version of Infinispan.

For now version 1.1.x is available on the dev-preview channel but you should switch your Operator subscription to 
the 1.1.x channel before the next release to continue receiving updates.

If you use the Automatic Approval upgrade policy on OpenShift, your cluster is now running Infinispan Operator version 1.1.2 
with the Infinispan 10.1.7.Final server image.

== Get it, Use it, Ask us!

Try the
https://github.com/infinispan/infinispan-simple-tutorials/tree/operator-1.1.x/operator[simple tutorial for 1.1.x].

You can https://github.com/infinispan/infinispan-operator/issues[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

