---
layout: blog
title: The developer Conference Sao Paulo
permalink: /blog/:year/:month/:day/infinispan-tdc-sp
date: '2020-08-28T12:00:00.000-00:00'
author: guslira
tags: [ "presentation", "quarkus", "event"]
---

== The Developer Conference Sao Paulo

Dear Infinispan community,

=== What is The Developer’s Conference?
The Developer’s Conference (TDC) is the largest event related to software development in Brazil connecting meetup and event organizers, speakers, companies and sponsors on a single platform, empowering the local ecosystem of each region it's realized.

TDC is a very dynamic conference aimed to present the most important topics according to local and international needs and, for this reason, there are more than ten parallel tracks a day.

This event takes place once a year in some cities in Brazil, but this year the event will be totally online due to COVID-19 impact.

Red Hat will be present on this event with 6 principal lectures and one room occurring simultaneously throughout the event.
We will have an Infinispan presentation showing some important features, what's new, demos and Quarkus integration at Red Hat sponsor room.

=== When will the Infinispan presentation happen?

.Friday, 28th August
[.table]
|===
|Hour | Timezone

|16h40
|BRT (GMT-3)

|17h40
|EDT (UTC-4)

|20h40
|BST (UTC+1)

|21h40
|CEST (UTC+2)
|===
