---
layout: blog
title: Infinispan Server Tutorial
date: '2020-07-28T12:00:00.000-00:00'
author: Katia Aresti
tags: [ "tutorial", "learning", "server" ]
---

= Infinispan Server Tutorial

Dear Infinispan community,

If you are wondering how to start with Infinispan Server from your Java Application,
a new https://infinispan.org/infinispan-server-tutorial/[Tutorial] is available.
This tutorial covers the essentials to get started with Infinispan Server and
takes around half an hour to complete.

In this tutorial you will learn how to:

. Run Infinispan Server.
. Access and use the Infinispan Console.
. Create Infinispan caches.
. Read and write data as primitive types and Java objects.
. Add lifespans to entries so data expires.
. Deploy client listeners to get event notifications.
. Search the data store for specific values.
. Use out-of-the-box testing with Junit 5 for verification.

Complete the tutorial, ask us anything about it, give us feedback
and feel free to share it!

== Get it, Use it, Ask us!

Please https://infinispan.org/download/[download],
https://issues.redhat.com/projects/ISPN[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].
