---
layout: blog
title: Infinispan Operator 1.1.0 is out!
date: '2020-01-24T12:00:00.000-00:00'
author: Galder Zamarreño
tags: [ "release", "operator" ]
---

We're pleased to announce
https://operatorhub.io/operator/infinispan[version 1.1.0 of the Infinispan Operator]
for Kubernetes and OpenShift.

This release includes a bunch of very exciting features! Let's dig into them:

== Full Lifecycle

Infinispan Operator 1.1.0 is rated at the `Full Lifecycle` capacity level, which 
means the Operator now provides advanced cluster management capabilities and 
functionality to handle demanding workloads.

One of the key new features in this release is graceful shutdown, which lets 
you bring clusters down safely to avoid data loss.

During cluster shutdown, caches can passivate in-memory entries 
to persistent storage along with the internal Infinispan state that maps 
which nodes own which entries. When you bring Infinispan clusters back, 
all your data is restored to memory.

Check out the https://infinispan.org/infinispan-operator/master/operator.html#shutting_down-start[Graceful Shutdown]
docs for more information.

Graceful shutdown also enables the Infinispan Operator to 
perform reliable upgrades.

When a new version of the Infinispan Operator starts,
it checks for running Infinispan clusters that were created by an older Operator version.

If the Operator detects a cluster that requires upgrade, it invokes a graceful shutdown 
on the cluster and then brings it back with the new Infinispan version.

You can perform upgrade manually or automatically with the 
https://docs.openshift.com/container-platform/4.3/operators/understanding-olm/olm-understanding-olm.html[Operator Lifecycle Manager] on OpenShift.

Note that Operators installed via the OperatorHub on OpenShift Container Platform are managed by the Operator Lifecyle Manager.

== Cache vs DataGrid

This version of the Infinispan Operator delivers Cache and DataGrid services.

By default the Operator starts Infinispan clusters as Cache services, which 
provides a quick way to set up in-memory caching that stores data off-heap and
keeps single copies of data in the cluster.

DataGrid services, on the other hand, are suited to more advanced use cases where
you control and define the configuration that you need.

== Cross-Site Replication

The Infinispan Operator simplifies cross-site replication set up with DataGrid services
so you can back data up between separate Kubernetes or OpenShift clusters.

All you need to do is specify which type of external Kubernetes service to expose,
the list of all backup locations, access secrets, and the local site name.

Find out more at:
https://infinispan.org/infinispan-operator/master/operator.html#configuring_backup_sites[Cross-Site Replication]

== Automatic TLS configuration

If you're running on Openshift and have a service that serves certificates,
the Operator automatically asks for certificates sets up TLS for your
endpoint connections. Encrypted by default with zero effort!

== Get it, Use it, Ask us!

Try the
https://github.com/infinispan/infinispan-simple-tutorials/tree/master/operator[simple tutorial]
for the Operator, which has been updated for this version.
The tutorial shows how to install the Operator manually,
but it can also be installed via the Operator Hub on OpenShift.

You can https://github.com/infinispan/infinispan-operator/issues[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

Finally, a detailed list of issues and features for this version can be found
https://github.com/infinispan/infinispan-operator/issues?q=milestone%3A1.1.0+is%3Aclosed[here].
