---
layout: blog
title: Infinispan 12.0.1.Final
permalink: /blog/:year/:month/:day/infinispan-11
date: '2021-02-12T12:00:00.000-00:00'
author: remerson
tags: [ "release" ]
---

= Infinispan 12.0.1.Final "Lockdown"

Dear Infinispan community,

we hope you've been enjoying all the new goodies included in our latest major release, Infinispan 12.

We now have a brand new micro release for you which addresses a number of issues.

The following list shows what we have fixed:

== Component Upgrade

    https://issues.redhat.com/browse/ISPN-12729[ISPN-12729] - Upgrade console to 0.13.1.Final

== Enhancement
    https://issues.redhat.com/browse/ISPN-12370[ISPN-12370] - Implement proper form login and digest login
    https://issues.redhat.com/browse/ISPN-12636[ISPN-12636] - Implicit connectors for the single-port endpoint
    https://issues.redhat.com/browse/ISPN-12718[ISPN-12718] - Add addtional DEBUG logs to Backup/Restore operations

== Feature Request
    https://issues.redhat.com/browse/ISPN-12660[ISPN-12660] - Add property to disable test execution

== Bug
    https://issues.redhat.com/browse/ISPN-12548[ISPN-12548] - Replicated cache get ignores value in zero-capacity nodes
    https://issues.redhat.com/browse/ISPN-12651[ISPN-12651] - CacheEntryCloudEventsTest test failures
    https://issues.redhat.com/browse/ISPN-12654[ISPN-12654] - Get entry broken in protobuf caches
    https://issues.redhat.com/browse/ISPN-12658[ISPN-12658] - Fix IracWriteSkewTest test
    https://issues.redhat.com/browse/ISPN-12659[ISPN-12659] - StatsTest random failures
    https://issues.redhat.com/browse/ISPN-12661[ISPN-12661] - Licenses are not properly generated in console
    https://issues.redhat.com/browse/ISPN-12662[ISPN-12662] - Functional commands break in replicated caches on zero-capacity nodes
    https://issues.redhat.com/browse/ISPN-12663[ISPN-12663] - LocalIndexSyncStateTransferTest random failures
    https://issues.redhat.com/browse/ISPN-12666[ISPN-12666] - ReplicationIndexTest random failures
    https://issues.redhat.com/browse/ISPN-12667[ISPN-12667] - GlobalState incompatibility between 11.x and 12.x
    https://issues.redhat.com/browse/ISPN-12669[ISPN-12669] - Tests failing due to relying on published images
    https://issues.redhat.com/browse/ISPN-12700[ISPN-12700] - CLI Batch files returns exit code 0 on error
    https://issues.redhat.com/browse/ISPN-12709[ISPN-12709] - Cannot retrieve the keyset of a cache (ISPN000287)
    https://issues.redhat.com/browse/ISPN-12710[ISPN-12710] - IllegalArgumentException in VoidResponseCollector: Self-suppression not permitted
    https://issues.redhat.com/browse/ISPN-12716[ISPN-12716] - Hot Rod iteration shouldn't require ADMIN permission
    https://issues.redhat.com/browse/ISPN-12719[ISPN-12719] - When a value is json but not protobuf the console fails
    https://issues.redhat.com/browse/ISPN-12724[ISPN-12724] - Hot Rod client has too many Elytron dependencies

Task
    https://issues.redhat.com/browse/ISPN-12681[ISPN-12681] - Upgrade logo in Operator Hub

