---
layout: blog
title: Infinispan 13.0.0.CR1
permalink: /blog/:year/:month/:day/infinispan-11
date: '2021-09-23T12:00:00.000-00:00'
author: karesti
tags: [ "release" ]
---

= Infinispan 13.0.0.CR1

Dear Infinispan community,

We've just released 13.0.0.CR1 which comes loaded with quite a few features, improvements and bug fixes.
Before fully blogging on specific features, here is a non exhaustive list of features what you will get in Infinispan 13.

== Caches configuration
Caches configuration is not inmutable anymore. We can update properties at runtime.

== Rolling upgrades
Rolling upgrades operations with the REST API, CLI and the Operator.

== Rebalancing operations
Enabling and disabling rebalancing for caches and clusters can be done from the REST API, CLI and
the Web Console.

== Persistence
* Change SoftIndexFileStore to be the Infinispan default file store
* SQL Store

== Cross-Site Replication
* Improved Cross-Site statistics
* Improved Cross-Site logging view
* Cluster Cross Site replication from the Web Console

== Query
* Support for local query operations
* Delete by query

== Documentation
* Hot Rod Client JS documentation
* Simple code tutorials documentation
* Improved Encoding and Marshalling documentation
* Replacement for integration guide with a Spring guide and a Hibernate guide
* Soft Index File Store updates
* Query focused documentation
* Performance documentation

