---
layout: blog
title: Infinispan 12.1.0.Final
permalink: /blog/:year/:month/:day/infinispan-12-final
date: '2021-04-05T12:00:00.000-00:00'
author: ttarrant
tags: [ "release" ]
---

== Infinispan 12.1.0.Final

Dear Infinispan community,

one of the surprises in your chocolate egg this year is a brand new final release. 
Infinispan 12.1 https://en.wikipedia.org/wiki/Taedonggang[Taedonggang] includes a bunch of new features and fixes.

=== Out-of-the-box authorization in the server

The biggest change is the fact that the server now enables authorization right from the start, including a set of predefined roles.
By default this only affects management ops and it can be easily disabled.

Head over to https://infinispan.org/docs/stable/titles/server/server.html#authorization for details on this feature and how to tune it to your own needs.


=== Configuration

Infinispan can now load configuration as YAML, as well as XML and JSON.

=== Soft-Index File Store

The Soft-Index File Store (or SIFS for short) is one of our file-based stores, and it has received a number of improvements such as segmentation and non-blocking. 
Additionally, if you are lucky enough to have some pmem hardware, this file-store can support it via the very awesome https://github.com/jhalliday/mashona[Mashona library].
We hope to make this our default file-store in the future (replacing the Single File Store).

=== Server protocol management

You can now enable/disable protocol endpoints at runtime or use https://infinispan.org/docs/stable/titles/server/server.html#endpoint_ipfilter[IP filtering] for fine-grained access control. 

=== Console

The console is now fully aware of the server authorization roles (if enabled).

=== CLI

The CLI is now available as https://github.com/infinispan/infinispan-quarkus/releases[native builds] for Linux and MacOS.

=== Cross Site Replication




=== Images

* A natively compiled version of the CLI is now available as a container via the https://quay.io/repository/infinispan/cli[infinispan/cli] image.
* The server images have also added support for configuring zero-capacity as well as allowing JGroups properties to be overridden at runtime.

=== Operator


== Documentation



== Release notes and upgrading

You can look at the detailed https://issues.redhat.com/secure/ReleaseNote.jspa?FIXME[release notes] to see what has changed since CR1.
If you are upgrading from a previous version of Infinispan, please checkout our https://infinispan.org/docs/stable/titles/upgrading/upgrading.html[Upgrading guide].

== What's next ?

Our next release, 13.0, should happen during the summer, and will hopefully introduce a new API which will make using Infinispan much easier, as well as a number of other improvements across the board. As usual, look out for blog postings about upcoming highlights. If you'd like to contribute, just get in touch.
