---
layout: blog
title: Infinispan 13.0.0.CR1
permalink: /blog/:year/:month/:day/infinispan-11
date: '2021-09-23T12:00:00.000-00:00'
author: karesti
tags: [ "release" ]
---

= Infinispan 13.0.0.CR1

Dear Infinispan community,

We've just released 13.0.0.CR1 which brings you several new features along with a number of enhancements and bug fixes.
Here is a non-exhaustive list of Infinispan 13 has in store:

== Mutable cache configuration
You can now update cache configuration at runtime with the CLI.

== Improved cluster upgrades
We've done quite a lot of work on rolling upgrade operations in Infinispan 13, making the process smoother from the REST API, CLI, and with our Kubernetes Operator.

== Re-balancing operations
Control cluster topology re-balancing from the REST API, CLI, and Console.

== Persistent storage improvements

* File-based caches stores now default to SoftIndexFileStore.
* We've added a new SQL cache store.

== Cross-site replication

For global Infinispan clusters, this release brings a number of improvements:

* Cross-site replication operations from the Console.
* Additional statistics for increased observability.
* Better logging details for cross-site cluster views.

== Queries

* Added support for local query operations.
* Ability to delete cache entries through query operations.

== Helm charts

We've added an Infinispan Helm chart for deploying clusters to Kubernetes.

== Documentation and tutorials

We've made a number of documentation improvements this release, including:

* A new guide for Hot Rod JS clients.
* Better organization and documentation for Infinispan simple tutorials.
* Replaced the Integration Guide with a dedicated guide for Spring users as well as a guide for Hibernate caches.
* A brand new guide for Indexing and Querying.
* Overhauled and updated Configuration Guide.
* Additional JSON and YAML configuration examples.

