---
layout: blog
title: Infinispan 12.1.0.Final
permalink: /blog/:year/:month/:day/infinispan-12-1-0-final
date: '2021-04-05T12:00:00.000-00:00'
author: ttarrant
tags: [ "release" ]
---

= Infinispan 12.1.0.Final

Dear Infinispan community,

As a belated surpirse in your chocolate egg this year is a brand new final release.
Infinispan 12.1 https://en.wikipedia.org/wiki/Taedonggang[Taedonggang] includes a bunch of new features and fixes.

== Out-of-the-box authorization in the server

The biggest change is the fact that the server now enables authorization right from the start, including a set of predefined roles.
By default this only affects management ops and it can be easily disabled.

Head over to https://infinispan.org/docs/stable/titles/server/server.html#authorization for details on this feature and how to tune it to your own needs.


== Configuration

Infinispan can now load configuration as YAML, as well as XML and JSON.

== Soft-Index File Store

The Soft-Index File Store (or SIFS for short) is one of our file-based stores, and it has received a number of improvements such as segmentation, non-blocking and requiring no additional threads.
Additionally, if you are lucky enough to have some persistent memory hardware, this file-store can support it via the very awesome https://github.com/jhalliday/mashona[Mashona library].
We hope to make this our default file-store in the future (replacing the Single File Store).

== Server protocol management

You can now enable/disable protocol endpoints at runtime or use https://infinispan.org/docs/stable/titles/server/server.html#endpoint_ipfilter[IP filtering] for fine-grained access control.

== Console

The console is now fully aware of the server authorization roles (if enabled) and many fixes are included.

== CLI

The CLI is now available as https://github.com/infinispan/infinispan-quarkus/releases[native builds] for Linux and MacOS.

== Cross Site Replication

You can now enable automatic Cross Site https://infinispan.org/docs/stable/titles/xsite/xsite.html#xsite_state_transfer-xsite[state transfer] for asynchronous backup strategy.

== Spring

Our Spring Cache and Spring Session integration now allows user keys and values to be stored in https://infinispan.org/docs/stable/titles/developing/developing.html#configuring_protobuf_encoding-data[Protostream] format.
However, full integration with the Infinispan Spring Boot Starter is landing in the next minor release. Stay tuned!

== Marshalling/ProtoBuf
The latest ProtoStream release 4.4.0.Beta3 includes support for marshalling arrays and collections, built-in support for several community requested types (UUID, BigDEcimal,...), a new method in ProtobufUtil for computing message size (without actually encoding the message) and a lot of bug fixes. This release also provides it’s own protobuf encoder and removes the dependency on protobuf-java artifact which was previously used for encoding the stream (without being exposed by the API).


== Images
We now provide an  image containing a natively compiled version of the Infinispan CLI at quay.io/infinispan/cli

== Operator
In addition to numerous fixes, the operator has added many new features. Most notably:

* Grafana Dashboard
* Batch CR
* Custom library support
* Custom labels on Resources created by Operator
* Disable Authentication Option
* Decouple user and operator endpoint authentication

== Documentation

We’ve made a lot of updates to our documentation this release, with lots more task-oriented content for new features and capabilities. Server credential stores, refactored authorization (RBAC) configuration, Operator Batch CR, Backup and Restore CRs, custom code deployments, automatic cross-site state transfer, querying values, configuring Protobuf annotations for marshalling… Hopefully you’ll find all the answers you need for using Infinispan 12.1.

One of the big highlights for docs in this release are the new tabbed configuration snippets we’re going to start adding. Right now you can find an example of tabbed configuration in the REST API docs here: https://infinispan.org/docs/dev/titles/rest/rest.html#cache_configuration

We’ve also done a lot of housekeeping in this release to make sure configuration examples are up to date and valid. In the next release you can expect to see more improvements there as well as a new title to improve our documentation around encoding and how Infinispan uses Protobuf.

As always, thanks for reading and get in touch if you have comments, feedback, or suggestions on our documentation.

== Release notes and upgrading

You can look at the detailed https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310799&version=12353337E[release notes] to see what has changed since CR1.
If you are upgrading from a previous version of Infinispan, please checkout our https://infinispan.org/docs/stable/titles/upgrading/upgrading.html[Upgrading guide].

== What's next ?

Our next release, 13.0, should happen during the summer, and will hopefully introduce a new API which will make using Infinispan much easier, as well as a number of other improvements across the board. As usual, look out for blog postings about upcoming highlights. If you'd like to contribute, just get in touch.
