---
layout: blog
title: Infinispan Native CLI
permalink: /blog/:year/:month/:day/infinispan-cli-image
date: '2021-05-21T12:00:00.000-00:00'
author: remerson
tags: [ "docker", "cli", "containers", "quarkus", "native"]
---

== Native CLI Image

Starting with Infinispan 12, we provide a natively compiled version of the Infinispan CLI.

This can be consumed as a native binary or via a container image.

=== Usage
. Start a Infinispan server instance so that the CLI has an endpoint to connect to:
----
docker run -it -p 11222:11222 -e USER="user" -e PASS="pass" quay.io/infinispan/server:12.1
----

=== Container
[start=2]
. Launch the CLI image and connect to the server image:

----
docker run --net=host -it --rm quay.io/infinispan/cli:12.1 -c http://127.0.0.1:11222
----
[start=3]
. Enter the "user" and "pass" credentials, for the username and password respectively.

TIP: The container's endpoint is the CLI binary, which lets you pass CLI arguments straight to the image, e.g. `quay.io/infinispan/cli:12.1 --version`

=== Binary
Native CLI binaries for Linux, Mac and Windows can be downloaded https://github.com/infinispan/infinispan-quarkus/releases/tag/12.1.3.Final[here].

[start=2]
. Download and extract the `.zip` for your desired platform:
.. https://github.com/infinispan/infinispan-quarkus/releases/download/12.1.3.Final/infinispan-cli-12.1.3.Final-linux-amd64.zip[Linux]
.. https://github.com/infinispan/infinispan-quarkus/releases/download/12.1.3.Final/infinispan-cli-12.1.3.Final-darwin-amd64.zip[Mac]
.. https://github.com/infinispan/infinispan-quarkus/releases/download/12.1.3.Final/infinispan-cli-12.1.3.Final-windows-amd64.zip[Windows]

. Start the CLI and connect to the server container:
.. Linux & Mac: `./ispn-cli -c http://127.0.0.1:11222`
.. Windows (Powershell): `& ".\ispn-cli.exe" -c http://127.0.0.1:11222`
