---
layout: blog
title: Infinispan 14.0.0.Dev03
permalink: /blog/:year/:month/:day/infinispan-14
date: '2022-05-27T12:00:00.000-00:00'
author: ttarrant
tags: [ "release", "development" ]
---

= Infinispan 14.0.0.Dev03

Dear Infinispan community,

Infinispan 14 development release 03 is here! We plan to release Infinispan 14 Final this summer, but we want to share a preview of what's coming.

== Java 11

Infinispan now requires Java 11 to run (it was only needed to build it before). This means we can use and expose all of the great new APIs that were added, such as `java.util.concurrent.Flow` which provides a standard interface for all things reactive.
Which brings us to the...

== New API

We have finalized the design of our new user-facing API, which brings the following, much-needed, features:

* a common API for both embedded and remote
* clean separation between sync and async APIs, as well as a link:https://smallrye.io/smallrye-mutiny/[Mutiny] variant which blends beautifully with all the great things happening over in link:https://quarkus.io/[Quarkus].
* a single entry-point to access all of the data-structures that we support (caches, counters, locks, multimaps, etc)
* our own annotations for indexing entity fields (see below for details)

We are now working on implementing this API for the remote Hot Rod client, while the implementation for embedded will be done in Infinispan 15.


== JGroups 5

Upgrading to Java 11 also allows us to upgrade to JGroups 5.x, which brings a bunch of improvements:

* Improved failure-detection protocols (`FD_ALL3`, `FD_SOCK2`)
* The Random Early Drop protocol (`RED`), which starts dropping messages on the send side when the queue becomes full to prevent message storms caused by unneeded retransmissions.
* Lots more.

== RAFT

We've integrated JGroups' RAFT implementation which will be used to provide strong CP
counters.


== Jakarta EE

JavaEE is dead. Long-live link:https://jakarta.ee/[JakartaEE]. Wherever we used to depend on `javax` APIs, we now depend on their `jakarta` equivalent. We still provide compatibility artifacts for legacy deployments.


== Hibernate ORM 6.0 compatibility

Infinispan's Hibernate ORM second-level cache (2LC) implementation has been upgraded to work with Hibernate 6.0.


== Indexing and Query

Lots has been happening in the land of indexing and querying.

* Upgraded Hibernate Search to 6.1 and Lucene 8.11.
* Brand-new annotations for indexing annotations in place of the old Hibernate annotations.
* Zero-downtime upgrading of ProtoBuf schemas with index regeneration
* The removal of the `@ProtoDoc` annotation to wrap indexing annotations for ProtoBuf generation

== Micrometer

We've replaced our use of SmallRye Metrics (an implementation of Microprofile Metrics), with the much better Micrometer.

== Server

* `RESP` endpoint: a Redis-compatible endpoint connector (implementing the RESP 3 protocol) with support for a subset of commands: `set`, `get`, `del`, `mget`, `mset`, `incr`, `decr`, `publish`, `subscribe`, `auth`, `ping`. The connector integrates with our security and protocol auto-detections, so that it is easily usable from our single-port endpoint. The implemented commands should be enough for basic usage. If you would like to see more, reach out via our community.
* Support for FIPS environments (PKCS#11)
* Support for masked and external credentials

== Console

The console now sports a cache-creation wizard: a feature-driven approach to configuring caches just the way you need them.


== Documentation

As always, the Infinispan team hope you find the documentation useful and complete. We’d love to hear from you and really value feedback from our community. If you think something is missing from the docs or spot a correction, please get in touch and we’ll get on it straight away.

== Release notes

You can look at the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310799&version=12347011[release notes] to see what has changed.
