---
layout: blog
title: Infinispan kNN Vector Search
permalink: /blog/:year/:month/:day/infinispan-vector-search
date: '2023-12-13T19:37:00.000-00:00'
author: fax4ever
tags: [ "search", "vector", "knn", "indexing", "embeddings" ]
---

= Infinispan kNN Vector Search

With Infinispan 15.0.0.Dev06, we have started to expose vector search capabilities using Infinispan's indexed queries.
Using the newly introduced kNN predicate, it is possible to find and order results by the k nearest neighbors of a given vector.

== Mapping the embeddings

The new `@Vector` indexing annotation is used to mark a field as an embedding. Embeddings are vector representations of data, according to a defined model.

The vector dimension is mandatory and should be defined at mapping time.
Other options that can be specified during mapping are:

* the similarity (distance) function
* the beam width
* the maximum number of connections. 

Bear in mind that these values affect the performance of the approximation algorithm that is used to compute the kNN search.

We support `byte[]` embeddings. Here is an example of mapping:

[source, java]
----
@Vector(dimension = 3)
@ProtoField(2)
public byte[] getByteVector() {
   return byteVector;
}
----

That corresponds to the Proto schema:

[source, proto]
----
/**
 * @Vector(dimension=3)
 */
optional bytes byteVector = 2;
----

We also support `float[]` embeddings. Here is an example of mapping:

[source, java]
----
@Vector(dimension = 3)
@ProtoField(3)
public float[] getFloatVector() {
   return floatVector;
}
----

That corresponds to the Proto schema:

[source, proto]
----
/**
 * @Vector(dimension=3)
 */
repeated float floatVector = 3;
----

== Searching the embeddings

The following query shows how to perform a kNN search using a supplied vector and a specific distance

[source, sql]
----
from Item i where i.byteVector <-> [7,7,7]~3
----

The query can be parameterized in several ways:

[source, java]
----
query = cache.query("from org.infinispan.query.model.Item i where i.byteVector <-> [:a,:b,:c]~3");
query.setParameter("a", 0);
query.setParameter("b", 2);
query.setParameter("c", 3);
hits = query.list();
assertThat(hits).extracting("code").containsExactly("c2", "c1", "c3"); // the order matters
----

Or you can pass the entire vector as a single parameter:

[source, java]
----
query = cache.query("from org.infinispan.query.model.Item i where i.floatVector <-> [:a]~:b");
query.setParameter("a", new float[]{7.1f, 7.0f, 3.1f});
query.setParameter("b", 3);
hits = query.list();
assertThat(hits).extracting("code").containsExactly("c5", "c6", "c4");
----

If the cache is distributed, the query will be a broadcast query, and it will aggregate all the results from all the nodes that contain shards of the indexes that are related to the search.
When we get the result as usual we get all the metadata from the corresponding entities, so that the returning items can easily relate to the application domain.
