---
layout: blog
title: Infinispan 15.0.0.Dev06
permalink: /blog/:year/:month/:day/infinispan-15dev06
date: '2023-12-14T00:00:00.000-00:00'
author: ttarrant
tags: [ "release", "development" ]
---

= Infinispan 15.0.0.Dev06


== Redis endpoint

The Redis endpoint now implements most of the core Redis commands and data structures (strings, sets, lists, hashes and sorted sets), as well as implementing
clustering and CRC16 slots.

== kNN Vector search

Infinispan can now perform indexed kNN vector searches. See our recent https://infinispan.org/blog/2023/12/13/infinispan-vector-search[blog post] for more information.

== Infinispan Web Console

The console has gained an access management section that lets you create, update, and delete roles, as well as assign access to principal mappers.

== GraalVM feature

A GraalVM native-image https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/hosted/Feature.html[Feature] is now available via the dedicated 
modules `infinispan-hotrod-graalvm` and `infinispan-embedded-graalvm`. 

== Hibernate ORM 6.3 2LC

Our second-level cache provider now supports Hibernate ORM 6.3.

== JCache is back!

While working on the Jakarta migration, we temporarily removed the JCache provider because of its optional dependency on CDI conflicting with the migration to Jakarta EE.
As of 15.0.0.Dev06, the JCache component is back, albeit without the CDI integration.


== When is the Final release coming?

We hope to have the final release of Infinispan 15 ready for consumption by the end of the year and we will be making regular development releases.


Get them from our https://infinispan.org/download/[download page].]

