---
layout: blog
title: Infinispan 16.0.4
permalink: /blog/:year/:month/:day/infinispan-16-0-4
date: '2025-12-17T00:00:00.000-00:00'
author: ttarrant
tags: [ "release", "final" ]
---

= Infinispan 16.0.4

We don't usually blog about micros, unless there are important things to mention, and in this case we have a couple
of significant changes to share with you.

== Spring Framework 7 and Spring Boot 4 support

Spring Framework 7 and Spring Boot 4 were released just after we tagged 16.0.0. We were planning on releasing support
for these with the 16.1 release at the beginning of February, but we decided it was too important to wait until
then.
16.0.4 includes artifacts for both Spring 7 / Boot 4 and Spring 6 / Boot 3. See the
https://infinispan.org/docs/stable/titles/spring/spring.html[documentation] for details

== Metrics changes

We forgot to make some changes to the default metrics configuration attributes during the 16.0 development cycle, even
though that was our intention all along.

* JVM metrics are no longer registered by default in embedded mode, as that should be the job of the application and
not the library.
* Cache names are now included in metrics as tags as opposed to names, which should make querying and charting easier
* Legacy metrics name prefixes (base and vendor) have been replaced with more appropriate library names.

All these can be reverted to their old configuration if needed, but trust us: the new defaults are better.

== Release notes

You can look at the https://github.com/infinispan/infinispan/releases/tag/16.0.4[release notes] to see what was changed
since our previous release.

Get them from our https://infinispan.org/download/[download page].

