# Default page title
title: Infinispan

# Project id name
project: infinispan

# Project full name
project_name: Infinispan

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

asciidoctor:
  :attributes:
    icons: font
    sectanchors: true
    toclevels: 3
    numbered: true
    docinfo: ''
    source-highlighter: coderay
    backend: html5
    doctype: book    
    ## Leave this empty!!
    imagesdir: ''
    experimental: true
# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community      
    # jborg_fonts_url: /cache/static.jboss.org/theme/fonts
    # jborg_images_url: /cache/static.jboss.org/theme/images
    # jborg_js_url: /cache/static.jboss.org/theme/js
    # project_images_url: /cache/static.jboss.org/images/example
    # bootstrap_css_url: /stylesheets/bootstrap-community
    # bootstrap_js_url: /javascripts/bootstrap-community
  staging:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community
    base_url: http://infinispan.github.io
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.4/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.4/bootstrap-community
    base_url: http://infinispan.github.io
    google_analytics: UA-8601422-1
    deploy:
      host: github_pages
      branch: master
