---
layout: blog
title: 'Single lock owner: an important step forward'
date: '2011-11-09T12:57:00.000-08:00'
author: Mircea Markus
tags: [ "radargun",
"transactions",
"locking",
"deadlock detection",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-7886295445675479442
blogger_orig_url: https://blog.infinispan.org/2011/11/single-lock-owner-important-step.html
---
The single lock owner is a highly requested Infinispan improvement. The
basic idea behind it is that, when writing to a key, locks are no longer
acquired on all the nodes that own that key, but only on a single
designated node (named "main owner").


== How does it help me?


Short version: if you use transactions that concurrently write to the
same keys, this improvement significantly increases your system'
throughput.


Long version: If you're using Infinispan with transactions that modify
the same key(s) concurrently then you can easily end up in a deadlock. A
deadlock can also occur if two transaction modify the same key at the
same time - which is both inefficient and counter-intuitive. Such a
deadlock means that at one transaction(or both) eventually rollback but
also the lock on the key is held for the duration of a
lockAquistionTimout config option (defaults to 10 seconds). These
deadlocks reduces the throughput significantly as transactions threads
are held inactive during deadlock time. On top of that, other
transactions that want to operate on that key are also delayed,
potentially resulting in a cascade effect.


== What's the added performance penalty?


The only encountered performance penalty is during cluster topology
changes. At that point the cluster needs to perform some additional
computation (no RPC involved) to fail-over the acquired locks from
previous to new owners.
Another noticeable aspect is that locks are now being released
asynchronously, after the transaction commits. This doesn't add any
burden to the transaction duration, but it means that locks are being
held slightly longer. That's not something to be concerned about if
you're not using transactions that compete for same locks though.
We plan to benchmark this feature using
http://radargun.sourceforge.net/[Radargun] benchmark tool - we'll report
back!


== Want to know more?


You can read the
http://community.jboss.org/wiki/SingleNodeLockingModel[single lock owner
design wiki] or/and follow the JIRA
https://issues.jboss.org/browse/ISPN-1137[JIRA] discussions.
