---
layout: blog
title: 5.1.0.BETA1 "Brahma" is out with reworked transaction handling
date: '2011-10-04T06:02:00.000-07:00'
author: Galder Zamarreño
tags: [ " transactions" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-8780699372567464510
blogger_orig_url: https://blog.infinispan.org/2011/10/510beta1-brahma-is-out-with-reworked.html
---
It's been a frantic couple of weeks at _chez_ Infinispan with loads of
hacking, presentations preparation, team meetings...etc and we're now
proud to release Infinispan 5.1.0.BETA1 _"Brahma"._

For this first beta release, the transaction layer has been redesigned
as explained by Mircea in
http://infinispan.blogspot.com/2011/10/transaction-remake-in-infinispan-51.html[this
blog post]. This is a very important step in the process of implementing
some key locking improvements, so we're very excited about this! Thanks
Mircea :)

There's a bunch of other little improvements, such as avoiding the use
of thread locals for cache operations with flags. As a result,
optimisations like the following are now viable:

[source,java]
----
AdvancedCache cache = ...
Cache forceWLCache = cache.withFlags(Flag.FORCE_WRITE_LOCK);
forceWLCache.get("voo");
forceWLCache.put("voo", "doo");
...
----

Previously each cache invocation would have required withFlags() to be
called, but now you only need to do it once and you can cache the
"flagged" cache and reuse it.

Another interesting little improvement is available for JDBC cache store
users. Basically, database tables can now be discovered within an
implicit schema. So, if each user has a different schema, the tables
will be created within their own space. This makes it easier to manage
environments where the JDBC cache store is used by multiple caches at
the same time because management is limited to adding a user per
application, as opposed to adding a user plus prefixing table names.
Thanks to Nicolas Filotto for bringing this up.

Please keep the
http://community.jboss.org/en/infinispan?view=discussions[feedback]
coming, and as always, you can
http://www.jboss.org/infinispan/downloads[download] the release from
here and you get further details on the issues addressed in the
https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310799&version=12313469[changelog].

Cheers,
Galder
