---
layout: blog
title: The JBoss Enterprise Data Grid tour!!
date: '2012-06-22T09:10:00.002-07:00'
author: Galder Zamarreño
tags: [ "conference",
"jdg",
"event",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-9157661077930811183
blogger_orig_url: https://blog.infinispan.org/2012/06/jboss-enterprise-data-grid-tour.html
---
It's exciting times at the Infinispan team! Here's some of my highlights
of the last few weeks and events coming up.



=== JBoss Enterprise Data Grid (based in Infinispan) presented in Spain's Red Hat JBoss Open Forum 2012



Yesterday I was in Madrid at http://www.redhatjboss.es/[Red Hat's JBoss
Open Forum 2012], where I presented about
http://www.redhat.com/products/jbossenterprisemiddleware/data-grid/[JBoss
Enterprise Data Grid] and Clustering in
http://www.redhat.com/products/jbossenterprisemiddleware/application-platform[JBoss
Enterprise Application Plattform 6]. 



This was a great opportunity to introduce these new products to a
Spanish audience, and as with everything in Spain, if you present in the
native language, people understand things better and are more likely to
get a better impression. 



Might sound odd, but presenting this stuff in another language other
than English, such as Spanish, is rather difficult even if you're a
native speaker. If you've developed software in English, you're used to
speaking about it in that language, but if you switch and you have to
talk about in another language, getting the fluency required to tell a
story (i.e. present something) takes a lot of preparation (write up
notes in that language!) and above all, rehearsing.



The effort was worth it though! Having finished my first presentation,
the JBoss Enterprise Data Grid one, I was non-stop talking to the
Spanish sales force, potential Spanish customers...etc for the rest of
the day, until I had to present again.



Last time I attended a JBoss middleware event in Spain was in Barcelona
in 2006. A long time has passed since then, but what Red Hat Spain's
JBoss Forum shows is that JBoss Middleware is back in the Iberian
peninsula, and it's there to stay for a long time!!



Special thanks to Lucas Ponce who helped out massively with the live
demos of both JBoss Enterprise Data Grid and JBoss Enterprise
Application Plattform 6, and thanks to the rest of Red Hat Spain team
who invited me to speak at the event.



=== JBoss World/Red Hat Summit and JUDCon in Boston



Heiko Rupp and I will be speaking about JBoss Enterprise Data Grid
monitoring with JBoss Operations Network, which we're both hugely
looking forward to! So, if you're around, don't miss the talk next
Thursday at 2.30pm EDT (abstract can be found
http://www.redhat.com/summit/sessions/jboss.html[here])



Cheers,

Galder






