---
layout: blog
title: Infinispan's distributed executors and Map/Reduce in spotlight at JUDCon and
  JBW
date: '2012-07-11T09:17:00.000-07:00'
author: Vladimir Blagojevic
tags: []
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1380154181411916972
blogger_orig_url: https://blog.infinispan.org/2012/07/infinispans-distributed-executors-and.html
---

JUDCon and JBoss World 2012 finished just a bit over a week ago in
Boston and were a complete blast. Several of my colleagues presented
their talks on the JBoss Data Grid and EAP clustering
performance. However, JUDCon and JBoss World were particularly appealing
to me personally as they made me aware of an increasing demand for large
scale computing, and in particular, use of Infinispan's own distributed
executors and Map/Reduce.

Anil Saldhana's
http://www.jboss.org/dms/judcon/2012boston/presentations/judcon2012boston_day1track3session2.pdf[talk]
about Big Data and Hadoop at JUDCon investigated the Hadoop setup in the
JBoss ecosystem and its use for log analysis. In our discussion Anil
contrasted the cumbersome Hadoop setup and API to our own Infinispan
Map/Reduce solution.

Mark Addy's JUDCon
http://www.jboss.org/dms/judcon/2012boston/presentations/judcon2012boston_day1track3session4.pdf["Infinispan
from POC to Production"] presentation was particularly engaging. Mark
and his team at C2B2 developed a search engine for a UK based global
on-line travel company using Infinspan as one of the key system
components. One of their use cases involved extracting a particular
pricing info from Infinispan cluster where distributed executors
framework was an excellent fit. Long story short the response time
improvement was an order of magnitude faster and the parallel execution
on Infinispan cluster using distributed executors saved the day. 

Erik Salter's presentation
http://www.redhat.com/summit/2012/presentations/jbossworld/["Infinispan
== Profit: A Start-up’s Success with JBoss Community
Software"] summarized interesting details about video on demand service
that Erik and his team developed for Cisco. Erik used the Infinispan
cluster for session setup and management and found distributed executors
and Map/Reduce to be a particularly good fit for a range of design trade
offs he and his team faced. 

Stay tuned for more good things to come in this area!

Cheers,
Vladimir
