---
layout: blog
title: 
date: '2015-08-05T00:45:00.000-07:00'
author: Unknown
tags: [ "radargun",
"release",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-7323902196441743407
blogger_orig_url: https://blog.infinispan.org/2015/08/radargun-2.html
---
=== [.underline]#RadarGun 2.1.0.Final#


I'm happy to announce RadarGun 2.1.0.Final is officialy out. RadarGun is
a multi purpose testing tool, which provides means to measure
performance and test features specific to distributed systems (data
grids, caches in particular).  

The release contains multiple fixes and improvements listed below:

* New plugins: jdg65, infinispan71, infinispan72, infinispan80, jcache
* Reporting improvements (perfrepo reporter, percentile chart, net/gross
throughput)
* GaussianKeySelector
* Enhanced listener support
* JMX invocation stage now supports setting attributes
* LogLogic improvements
* Enanced TopologyHistory & WaitForTopologySettle stage
* Better test coverage
* Multiple bug fixes

From this point on, the main development will continue in 3.x line. We
are preparing considerable design changes, so that RadarGun can be
easily utilized to measure performance of other areas as well (e.g.
JPA).



For more information about RadarGun, feel free to visit our
https://github.com/radargun/radargun/wiki[wiki page], or try
https://github.com/radargun/radargun/wiki/Five-Minute-Tutorial[five
minute tutorial]. In case of any issues, please refer to our
https://github.com/radargun/radargun/issues[issue tracker].



Thanks everyone for their contributions!
