---
layout: blog
title: New Functional Map API in Infinispan 8 - Introduction
date: '2015-08-21T03:08:00.000-07:00'
author: Galder Zamarreño
tags: [ " functional","introduction", "API", "lambda" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-957260515663968223
blogger_orig_url: https://blog.infinispan.org/2015/08/new-functional-map-api-in-infinispan-8.html
---
In Infinispan 8.0.0.Beta3, we have a introduced a new experimental API
for interacting with your data which takes advantage of the functional
programming additions and improved asynchronous programming capabilities
available in Java 8.

Over the next few weeks we'll be introducing different aspects of the
API. In this first blog post, we'll focus on why we felt there's a need
for a new approach, answering a few key questions.


=== ConcurrentMap and JCache


Map­-like key/value pair APIs have often been used for distributed
caching and in-­memory data grids. Initially,
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html[ConcurrentMap]
became popular but this was designed to be run within a single JVM, and
hence some of the operations suffered in distributed environments or
when persistence stores were attached. For example, methods such as
'https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-[_V
put(K, V)_]',
'https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#putIfAbsent-K-V-[_V
putIfAbsent(K, V)_]',
_'https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentMap.html#replace-K-V-[V
replace(K, V)]_' would force implementations to return the previous
value, but often this value is not needed yet this could be expensive to
transfer.

https://jcp.org/en/jsr/detail?id=107[JSR­-107] set out to improve on
this and came up with the
https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java[JCache]
specification which solved this particular problem separating operations
such ConcurrentMap's
'https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-[_V
put(K, V)_]' into two operations:
'https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L194[_void
put(K, V)_]' and
'_https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L224[V
getAndPut(K, V)]'_, and it applied the same logic to other operations
such as '_replace_' by providing an alternative
'_https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L459[getAndReplace(K,
V)]'_... etc.

However, even though JCache was designed with distributed caching in
mind, it still failed to provide an API to execute operations
asynchronously and hence avoid resource under­utilization by having
threads waiting for remote operations to complete.
'_https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L169[l​oadAll]'_ ​is
probably the only exception, and it would have been the perfect
candidate to return a
http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html[F​uture​]
or similar construct, but having to pass in a completion listener feels
a bit clunky and cannot be chained easily.

In my opinion, the best parts of JCache are
'__https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L559[i​nvoke]'__​
and
'https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L599[_i​nvokeAll_]'
methods. When you
look at them, you see a lot of potential to reimplement _get_, _put_,
_getAndPut_, _getAndReplace_, _putAll_,​ _getAll_, ​and many others
using these methods. In other words, as an implementer, all you should
need to implement is those two functions, and the rest would be
syntactic sugar for the user. Unfortunately, the way '_i​nvoke_' and
'_i​nvokeAll_' handle arguments is a bit clunky, and really,  it's just
screaming for lambdas to be passed in and
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html[C​ompletableFuture] instances to
be returned (Java 8!).

So, when Infinispan moved to Java 8, we decided to revisit these
concepts and see if we could come up with a better, distilled map­-like
interface to be used for as either a caching or data grid API.


=== New Functional Map API


Infinispan's
https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java[Functional
Map API] is a distilled map­like asynchronous API which uses lambdas to
interact with data.

===== Asynchronous and Lazy

Being an asynchronous API, all methods that return a single result,
return a
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html[CompletableFuture]
which wraps the result, so you can use the resources of your system more
efficiently by having the possibility to receive callbacks when the
CompletableFuture has completed, or you can chain or compose them with
other CompletableFuture. If you do want to block the thread and wait for
the result, just as it happens with a ConcurrentMap or JCache method
call, you can simply call
`https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#get--[_CompletableFuture.get()_]`
(for such situations, we are working on finding ways to avoid
unnecessary thread creation when the caller will block on the
CompletableFuture).

For those operations that return multiple results, the API returns
instances of a
​https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/Traversable.java[Traversable]
interface which offers a lazy pull­-style API for working with multiple
results. Although push­-style interfaces for handling multiple results,
such as RxJava, are fully asynchronous, they're harder to use from a
user’s perspective. T​raversable,​ being a lazy pull­-style API, can
still be asynchronous underneath since the user can decide to work on
the traversable at a later stage, and the Traversable implementation
itself can decide when to compute those results.

===== Lambda transparency

Since the content of the lambdas is transparent to Infinispan, the API
has been split into 3 interfaces for read­-only
(https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L106[R​eadOnlyMap])​,
read­-write
(https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L456[R​eadWriteMap])​
and write­-only
(https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L227[W​riteOnlyMap])​
operations respectively, in order to provide hints to the Infinispan
internals on the type of work needed to support lambdas.

For example, Infinispan has been designed in such way that our
'_C​oncurrentMap.​g​et(​)_' and '_JCache.​g​etAll(​)_' implementations
do not require locks to be acquired. These _get()_/_getAll()_ operations
are read-only operations, and hence if you call our functional map
R​eadOnlyMap's '_https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L144[eval(​)]_'
or
'_https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L176[e​valMany(​)]_'
operations, you get the same benefit. A key advantage of R​eadOnlyMap's
'_eval​()_' and '_e​valMany(​)_' operations is that they take lambdas as
parameters which means the returned types are more flexible, so we can
return a value associated with the key, or we can return a boolean if a
value has the expected contents, or we can return some metadata
parameters from it, e.g. last accessed time, last modified time,
creation time, lifespan, version information...etc.

Another important hint that is required to make efficient use of the
system is to know when a write-only operation is being executed.
Write­-only operations require locks to be acquired and as demonstrated
by JCache's
'https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L505[_void
removeAll()_]' and
`__https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L194[void
put(K, V)]__' or ConcurrentMap's
'https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putAll-java.util.Map-[_putAll()_]',
they do not require the previous value to be queried or read, which as
explained above is a very important optimization since reading the
previous value might require the persistence layer or a remote node to
be queried. WriteOnlyMap's
'https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L281[_eval()_]',
'https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L351[_evalMany()_]',
and
'https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L414[_evalAll()_]'
follow this same pattern with the added flexibility for the lambda to
decide what kind of write operation to execute.

The final type of operations we have are read­-write operations, and
within this category we find CAS-like (Compare­-And­-Swap) operations.
This type of operations require previous value associated with the key
to be read and for locks to be acquired before executing the lambda.
￼Most of the operations in ConcurrentMap and JCache operations fall
within this domain including:
'_https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#put-K-V-[V
put(K, V)]_',
'https://github.com/jsr107/jsr107spec/blob/v1.0.0/src/main/java/javax/cache/Cache.java#L283[_boolean
putIfAbsent(K, V)_]',
'_https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#replace-K-V-[V
replace(K, V)]_',
'_https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#replace-K-V-V-[boolean
replace(K, V, V)]_'...etc. ReadWriteMap's
'_https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L554[eval()]_',
'_https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L581[evalMany()]_'
and
'_https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/api/functional/FunctionalMap.java#L626[evalAll()]_'
provide a way to implement the vast majority of these operations thanks
to the flexibility of the lambdas passed in. So you can make CAS­-like
comparisons not only based on value equality but based on metadata
parameter equality such as version information, and you can send back
previous value or boolean instances to signal whether the CAS­-like
comparison succeeded.


=== $DEITY, I need to learn a new API!!!


This new functional Map­-like API is meant to complement existing
Key/Value Infinispan API offerings, so you'll still be able to use
ConcurrentMap or JCache standard APIs if that's what suits your use case
best.

The target audience for this new API is either:

. Distributed or persistent caching/in­-memory­ data­-grid users that
want to benefit from CompletableFuture and/or Traversable for async/lazy
data grid or caching data manipulation. The clear advantage here is that
threads do not need to be idle waiting for remote operations to
complete, but instead these can be notified when remote operations
complete and then chain them with other subsequent operations.
. Users wanting to go beyond the standard operations exposed by
ConcurrentMap and JCache, for example, if you want to do a replace
operation using metadata parameter equality instead of value equality,
or if you want to retrieve metadata information from values...etc.

Internally, we feel that this new functional Map­-like API distills the
Map­-like APIs that we currently offer (including ConcurrentMap and
JCache) and gets rid of a lot of duplication in our
https://docs.jboss.org/infinispan/8.0/apidocs/org/infinispan/AdvancedCache.html[AdvancedCache]
API (e.g.
'https://docs.jboss.org/infinispan/8.0/apidocs/org/infinispan/AdvancedCache.html#getCacheEntry-java.lang.Object-[_getCacheEntry()_]',
'https://docs.jboss.org/infinispan/8.0/apidocs/org/infinispan/commons/api/AsyncCache.html#getAsync-K-[_getAsync()_]',
'https://docs.jboss.org/infinispan/8.0/apidocs/org/infinispan/commons/api/AsyncCache.html#putAsync-K-V-[_putAsync()_]',
'_https://docs.jboss.org/infinispan/8.0/apidocs/org/infinispan/AdvancedCache.html#put-K-V-org.infinispan.metadata.Metadata-[put(K,
V, Metadata)]_'...etc), and hence down the line, we'd want all these
APIs to be implemented using the new functional Map­like API. By doing
that, we hope to reduce the number of commands that our internal
architecture implements, hence reducing our code base.

This new API also offers a new approach for passing per-invocation
parameters, and much more flexible Metadata handling compared to our
current approach. As we dig into this new API in next blog posts, we'll
explain the differences and advantages provided by these.


=== Functional Map API usage examples


To give you a little taste of what the API looks like, here is a
write-­only operation to associate a key with a value, whose
CompletableFuture has been chained so that when it completes, a
read­-only operation can be executed to read the stored value, and when
that completes, print it to the system output:


You can find more examples of this new API
in https://github.com/infinispan/infinispan/blob/master/core/src/test/java/org/infinispan/functional/decorators/FunctionalConcurrentMap.java[FunctionalConcurrentMap] and
https://github.com/infinispan/infinispan/blob/master/core/src/test/java/org/infinispan/functional/decorators/FunctionalJCache.java[FunctionalJCache]
classes, which are implementations of ConcurrentMap and JCache
respectively using the new Functional Map API.


=== Tell me more!!￼


Over the next few weeks I'll be posting examples looking at the finer
details of these new Functional Map APIs, but if you're eager to get
started, check the classes in org.infinispan.functional
package, https://github.com/infinispan/infinispan/blob/master/core/src/test/java/org/infinispan/functional/decorators/FunctionalConcurrentMap.java[FunctionalConcurrentMap]
and https://github.com/infinispan/infinispan/blob/master/core/src/test/java/org/infinispan/functional/decorators/FunctionalJCache.java[FunctionalJCache] which
are ConcurrentMap and JCache implementations based on these Functional
Map APIs, and
https://github.com/infinispan/infinispan/blob/master/core/src/test/java/org/infinispan/functional/FunctionalMapTest.java[FunctionalMapTest]
which demonstrates operations that go beyond what ConcurrentMap and
JCache offer.

Happy (functional) hacking :)

Galder
