---
layout: blog
title: Configuration management on OpenShift, Kubernetes and Docker
date: '2016-09-02T03:51:00.000-07:00'
author: Sebastian Łaskawiec
tags: []
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-30544979481083473
blogger_orig_url: https://blog.infinispan.org/2016/09/configuration-management-on-openshift.html
---
When deploying Infinispan on Docker based Cloud environments, the most
critical thing is how to manage configuration. In this blog post we'll
explore some of the options.

== Extending our Docker image

Creating your own Docker image based on jboss/infinispan-server is quite
simple. At first you need to prepare a configuration XML file, which is
shipped with Infinispan release. Go
to http://infinispan.org/download/[Infinispan download section] and grap
a server release corresponding to a chosen Docker image tag.  After
unpacking it, grab the configuration (I use cloud.xml as a template) and
introduce all necessary changes. 



Finally, build your image:





Now, that was quick! Wasn't it?

===== Using ConfigMaps with OpenShift

If you're using https://www.openshift.org/[OpenShift], there's a
sophisticated tool called
https://docs.openshift.org/latest/dev_guide/configmaps.html[ConfigMap].
A ConfigMap can store a configuration file (or a configuration
directory) and mount it somewhere in the Pod.

Use the command below to create a ConfigMap based on a configuration
file:




Now create Infinispan application based on the configuration below (you
can use 'oc create -f <file.yaml>' for this):



* (lines 50 - 52) - ConfigMap volume declaration
* (lines 45 - 47) - Mounting configuration
into _/opt/jboss/infinispan-server/standalone/configuration/custom_
* (line 22) - bootstrapping the Infinispan with custom configuration
(note there is no xml extension there)

===== Using ConfigMaps with Kubernetes

Kubernetes http://kubernetes.io/docs/user-guide/configmap/[ConfigMaps]
work exactly the same way as in OpenShift.



The command below creates a ConfigMap:



The second step is to create a Deployment with ConfigMap:



===== Conclusion

If you're using any Docker orchestration tool - have a look at provided
tools. OpenShift and Kubernetes ConfigMaps are really great for this.


However if you need a fine grained control - either extend our Docker
image (this is the preferred way) or simply fork and modify it.


Happy configuring and scaling!




