---
layout: blog
title: Infinispan 9.0 CR2 is out!
date: '2017-02-23T15:40:00.000-08:00'
author: Pedro Ruivo
tags: [
"release",
"release candidate",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-6591186462723574726
blogger_orig_url: https://blog.infinispan.org/2017/02/infinispan-90-cr2-is-out.html
---
Dear community.

We are one step closer to the final release of Infinispan 9: we gladly
announce the release of Infinispan 9.0.0.CR2.


== The highlights of this release are:

Many dependencies have been upgraded to the latest and greatest:

* JGroups 4.0.0.Final
* Apache Lucene 5.5.4
* Hibernate Search 5.7.0.Final
* Protostream 4.0.0.Alpha7 

Transactional caches changes:

* Removed asynchronous configuration since it won't be supported
anymore.
* Introduced EmbeddedTransactionManager: a basic transaction manager
implementation.

Query now supports java.time.Instant natively

Changes in the configuration;

Significant performance improvements for embedded and client/server
mode;

And finally, quite a few bug fixes preparing us for the final release !



You can read all about these in
the https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310799&version=12330030[release
notes.]

Keep an eye on
the http://infinispan.org/docs/dev/upgrading/upgrading.html[upgrade
guide] and start prepare your project for the final Infinispan 9
release.


So, please head over to the http://infinispan.org/download/[download
page] and try it out. If you have an issue, please report it in
our https://issues.jboss.org/projects/ISPN/summary[bug tracker], ask us
on the https://developer.jboss.org/en/infinispan/content[forum], or join
us for a friendly chat on the #infinispan IRC channel
on http://webchat.freenode.net/[Freenode.]

Regards,
Infinispan Team.
