---
layout: blog
title: '2017: A busy year for Infinispan evangelisation!'
date: '2017-12-21T06:00:00.000-08:00'
author: Galder Zamarreño
tags: [ " conference" ]
thumbnail: https://i.ytimg.com/vi/ATh1PuTho-M/0.jpg
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-5993299034504266679
blogger_orig_url: https://blog.infinispan.org/2017/12/2017-busy-year-for-infinispan.html
---
It's been a very busy year from an Infinispan evangelisation
perspective, so before the year ends, we wanted to round up the
conferences and user groups that featured Infinispan related talks. This
is a good opportunity to catch up on what we've been showing in our
Infinispan outings:

===== Patterns d’utilisation de systèmes in memory 

by https://twitter.com/emmanuelbernard[Emmanuel Bernard] and Galder
Zamarreño
@
http://blog.infinispan.org/2017/04/in-memory-data-grid-patterns-demos-from.html[Devoxx
France]

This was our first outing of the year with Emmanuel and I showing the
audience at Devoxx France the different use cases for data grids. This
was also the first time we showed swiss train related demos which we'd
improve throughout the year. Slides can be found
https://speakerdeck.com/galderz/patterns-dutilisation-de-systemes-in-memory[here]
and video below:




===== Big Data In Action with Infinispan

by Galder Zamarreño
@
http://blog.infinispan.org/2017/05/reactive-big-data-on-openshift-in.html[Great
Indian Developer Summit]
@
http://blog.infinispan.org/2017/06/back-from-berlin-buzzwords-video.html[Berlin
Buzzwords]
@
http://blog.infinispan.org/2017/09/devnation-live-video-and-slides.html[Red
Hat DevNation Live]

In this talk, I focused on the big data related use cases for
Infinispan. I showed how Infinispan could be used for near real-time
data processing using Continuous Querys, and how to analise data using
distributed Java Streams. Slides can be found
https://speakerdeck.com/galderz/big-data-in-action-with-infinispan[here]
and the demo
https://github.com/infinispan-demos/swiss-transport-datagrid[here]. The
video from the DevNation talk can be found here:




===== HACEP: Highly available and horizontally scalable complex event processing

by Ugo Landini, Sanne Grinovero, Andrea Leoncini, Andrea Tarocchi
@ Red Hat Summit

In this hands on lab, Ugo et al showed how to build a highly available
and scalable complex event processing engine with Red Hat JBoss BRMS and
and Red Hat JBoss Data Grid (the commercial supported version of
Infinispan). This workshop resulted in unmissable
https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/highly-available_complex_event_processing_with_red_hat_jboss_brms_and_red_hat_jboss_data_grid/highly_available_scalable_complex_event_processing_with_red_hat_jboss_brms[architecture
reference guide].

===== Learn how to build Functional Reactive Applications with Elm, Node.js and Infinispan

by Galder Zamarreño
@ Great Indian Developer Summit
@
http://blog.infinispan.org/2017/05/j-on-beach-unmissable-conference-for.html[J
On The Beach]



The aim of this talk is to demonstrate how Infinispan's Node.js client
could be combined with Elm and Infinispan server instances to build a
functional reactive application. The talk focused on how build a CRUD
application using Elm and Node.js technologies and using Infinispan
in-memory data grids for storing and querying information. Slides can be
found here:





===== Streaming Data Analysis with Kubernetes

by Galder Zamarreño

@ http://blog.infinispan.org/2017/10/thanks-basel-one-2017.html[Basel
One]



This talk is a spin off of the big data in action talk which focuses on
exploring in greater detail how streaming data can be analysed within a
Kubernetes orchestrated cluster. The demo can be
found https://github.com/infinispan-demos/streaming-data-kubernetes/tree/baselone-17[here] and
the slides here:


===== Data grids : descubre qué esconden los datos

by Galder Zamarreño

@
http://blog.infinispan.org/2017/11/back-from-madrid-jug-and-codemotion.html[Madrid
Java User Group]



This talk is a Spanish spin off the analytics part of the big data in
action talk. Not only did it showed how to use distributed Java Streams
to analyse data with Infinispan, but also demonstrated the capabilities
of Spark/Hadoop integrations. The demos can be
found https://github.com/infinispan-demos/swiss-transport-datagrid/blob/codemotion-madrid-17/live-events/madridjug17.md[here]
and
https://github.com/infinispan/infinispan-spark/blob/master/examples/twitter/README.md[here],
and the slides here:





===== Streaming Data : ni pierdas el tren, ni esperes en balde

by Galder Zamarreño

@
http://blog.infinispan.org/2017/11/back-from-madrid-jug-and-codemotion.html[Codemotion
Madrid]



A Spanish version of the streaming data analysis talk delivered in Basel
One.

[line-through]*This talk was recorded, so hoping for the video to be
available soon. *
*Update (2018/02/02):* The video is now available here:




In the mean time, the demo can be
found https://github.com/infinispan-demos/streaming-data-kubernetes/blob/codemotion-madrid-17/live-coding/codemotion-madrid-17.md[here] and
the slides here:


===== Streaming Data Workshop

by Katia Aresti, Thomas Segismont and Galder Zamarreño

@
http://blog.infinispan.org/2017/11/merci-duchess-et-devoxx.html[Duchess
France Meetup]

@ http://blog.infinispan.org/2017/11/merci-duchess-et-devoxx.html[Devoxx
Belgium]

@
http://blog.infinispan.org/2017/11/back-from-madrid-jug-and-codemotion.html[Codemotion
Madrid]



A hands-on workshop showing how to work with streaming data with
Infinispan and Vert.x, on top of OpenShift container platform. No videos
were recorded but you can follow this workshop step by step following
instructions
http://htmlpreview.github.io/?https://github.com/infinispan-demos/streaming-data-workshop/blob/master/workshop-steps/workshop.html[here].
The Github repository can be found
https://github.com/infinispan-demos/streaming-data-workshop[here] and
the latest slides here:




There's plenty the to keep you entertained between now and the new year!
:)

If you have any doubts about the talks above, or you encounter any
issues running the demos, do not hesitate
http://infinispan.org/community/[contacting us]! In the mean time, the
Infinispan team is working hard on Infinispan 9.2 as well as improving
our OpenShift integration.



Cheers,

Galder




