---
layout: blog
title: Infinispan 9.1 "Bastille"
date: '2017-07-14T12:41:00.000-07:00'
author: Tristan Tarrant
tags: [ "release",
"final",
]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-4317501012346850277
blogger_orig_url: https://blog.infinispan.org/2017/07/infinispan-91-bastille.html
---
Dear Infinispan users,

after 3½ months, we are proud to present to you our latest stable
release, Infinispan 9.1, codenamed
"https://revbrew.com/beer/archive/bastille[Bastille]".

While minor releases are traditionally evolutionary instead of
revolutionary, this release still comes loaded with a number of great
features:

== http://infinispan.org/docs/stable/user_guide/user_guide.html#scattered_mode[Scattered cache]

A new clustered cache, similar to a distributed cache, but with a higher
write throughput.

== http://infinispan.org/docs/stable/user_guide/user_guide.html#conflict-manager[Consistency Checker, Conflict Resolution and Automatic merge policies]

An overhaul to partition handling which allows much finer control about
whether to allow reads and writes in split clusters and how data is
reconciled when partitions are merged.

== http://infinispan.org/docs/stable/user_guide/user_guide.html#clustered_counters[Clustered Counters]

An implementation of clustered counters with both strong and weak
semantics, threshold events, optional persistence and bounding.
Currently these are only available in embedded mode, but they will be
usable over Hot Rod in Infinispan 9.2.

== Locked Streams

Locked streams allow you to run your stream processing operations
knowing that another update cannot be performed while the Consumer is
executed on an entry. Note this only works in non transactional and
pessimistic transactional caches (optimistic transactional caches are
not supported).

== API improvements

The compute(), computeIfPresent() and computeIfAbsent() methods on the
Cache interface are now implemented as proper distributed operations so
that they run local to the entries.
The DeltaAware interface for supporting granular clustered operations
has been deprecated in favour of functional commands.

== Persistence improvements

The CacheStore SPI now supports write batching. The JDBC, JPA, RocksDB,
Remote and File stores have been modified to take advantage of this. You
should see great benefits when using write-behind or when using putAll
operations.

== Remote query with JBoss Marshalling

Remote query now also works with Java entities annotated with Hibernate
Search annotations and JBoss Marshalling without requiring ProtoBuf.

== HTTP/2 and ALPN support on the REST endpoint

The REST endpoint has been completely rewritten so that it now supports
both HTTP/1.1 and HTTP/2 as well as
https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation[ALPN]
(even on Java 8). The new endpoint is also 30% faster during reads and
6% faster during writes.

== Hot Rod Java client improvements

The Java Hot Rod client now has proper entrySet(), keySet() and values()
implementations which iterate over the remote data instead of pulling it
all locally.
It is now also finally possible to create and remove caches directly
from the client.

== Server Administration console improvements

The console has received a number of updates for usability and
consistency. It is also finally possible to configure and manage the
remote endpoints.

== Component upgrades

Hibernate Search 5.8, JGroups 4.0.4, KUBE Ping 1.0.0.Beta1

== Bug fixes

We have also dropped the guillotine on a large number of bugs.

If all goes well, we plan to release Infinispan 9.2 at the end of
October, with lots of great updates.

So, head over to our http://infinispan.org/download/[download] page,
consult the
http://infinispan.org/docs/stable/upgrading/upgrading.html[upgrading
guide] and https://developer.jboss.org/en/infinispan/content[let us
know] about how you use Infinispan.

Cheers !

The Infinispan team
