---
layout: blog
title: Cluster Counter
date: '2017-07-21T09:33:00.000-07:00'
author: Pedro Ruivo
tags: [ "counter" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-5343955017767092509
blogger_orig_url: https://blog.infinispan.org/2017/07/cluster-counter.html
---
In Infinispan 9.1 we introduce the clustered counters. It is a counter
distributed and shared among all nodes in the cluster and today we are
going to know more about it.


== Installation

To use a counter in your Infinispan cluster, first you have to add the
maven dependency to your project. As you can see, it is simple as
doing:


After adding the module, you can retrieve the CounterManager and start
creating and using counters.


== CounterManager

Each CounterManager is associated to a CacheManager. But, before showing
how to use it, first we have some configuration to be done.

There are two attributes that you can configure: The num-owner - that
represents the number of copies of the counter's value in a cluster; and
the reliability - that represents the behavior of the counters in case
of partitions.

Below, is the configuration example with their default values.
XML:

Programatically:

Then, you can retrieve the CounterManager from the CacheManager, as
shown below, and start using the counters!



== Counter

A counter is identified by its name. Also, it is initialized with an
initial value (by default 0) and it can be persisted, if the value needs
to survive a cluster restart.



There are 2 types of counters: strong and weak counters.


== Strong Counters

The strong counter provides higher consistency. Its value is known
during the update and its updates are applied atomically. This allows to
set boundaries and provides conditional operation (as
compare-and-set).

=== Configuration

A strong counter can be configured in the configuration file or
programatically. They can be also created dynamically at runtime. Below
shows us how it can be done:

XML:

Programatically:

Runtime:



=== Use Case

The strong counter fits the following uses cases:

* Global Id Generator

Due to its strong consistency, it can be used as a global identifier
generator, as in the example below:



* Rate Limiter

If bounded, it can be used as a simple rate limiter. Just don't forget
to invoke reset()...



* Simply count "stuff"

Well, it is a counter after all...



== Weak Counters

The weak counter provides eventual consistency and its value is not
known during updates. It provides faster writes when comparing with the
strong counter.

===== Configuration

As in strong counter, the weak counter can be configure its name and its
initial value. In addition, a concurrency-level can be configure to set
the number of concurrent updates that can be handled in parallel. Below
shows us how to configure it:

XML:

Programatically:

Runtime:



===== Use Case

The main use case for the weak counter includes all scenarios where its
value isn't needed while updating the counter. For example, it can be
used to count the number of visits to some resource:



For more information, take a look at the
http://infinispan.org/docs/9.1.x/user_guide/user_guide.html#clustered_counters[documentation].
If you have any feedback, or would like to request some new features, or
found some issue, let us know via
the https://developer.jboss.org/en/infinispan/content[forum], https://issues.jboss.org/projects/ISPN[issue
tracker] or the #infinispan channel
onhttp://webchat.freenode.net/?channels=%23infinispan[ Freenode].
