---
layout: blog
title: 'Cache configuration inheritance: you''re no son of mine'
date: '2017-06-22T04:58:00.000-07:00'
author: Tristan Tarrant
tags: [ " configuration" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1238316106220715134
blogger_orig_url: https://blog.infinispan.org/2017/06/cache-configuration-inheritance-youre.html
---
Once upon a time Infinispan cache configurations were all orphans.

Actually, it wasn't as sad as that: they all shared a single parent -
the default cache. While this gave caches a limited form of inheritance,
it led to confusion as users weren't really aware of it and it was
impossible to turn it off: the limited gene pool was propagating
possibly unwanted traits to all of its children.


==== Templates and real configuration inheritance

Infinispan 7.2 finally introduced proper configuration templates and
inheritance. But there was a catch. Backwards compatibility dictated
that the "default mother of all caches" behaviour survived.


In the above example, the default cache is a replicated cache with a
file store. The distributed cache inherits the _"transactional"_
configuration. However, because of default inheritance present up to
Infinispan 8.2, the distributed-cache also ended up having a file store.
Confusing or what !?!
The best workaround was to never give it a specific configuration, let
Infinispan use its internal defaults and essentially avoid it. Just like
the black sheep in the family.


==== Bye bye default cache 

With Infinispan 9.0 we decided it was finally time to cut the umbilical
cord between the default cache and all the other caches: if you declare
one, it will never be used as default inheritance for every other cache.
In the above example, the distributed cache won't have a file store any
more.

We've gone even further: unless you declare a default cache, we will not
even set one up for you, not even one with default settings!

Aleksandr Sergeevich Serebrovskii, the Russian geneticist  who first
formulated the concept of the gene pool and the diversity benefits it
brings, would be proud of us.

