---
layout: blog
title: 'JDBC Migrator or: How I Learned to Stop Worrying About Buckets and Utilise
  the JdbcStringBasedStore!'
date: '2017-03-10T02:27:00.000-08:00'
author: Ryan Emerson
tags: [ "jdbc", "cache stores", "migration" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-8580712697275598944
blogger_orig_url: https://blog.infinispan.org/2017/03/jdbc-migrator-or-how-i-learned-to-stop.html
---
Infinispan 9 has introduced many improvements to its marshalling
codebase in order to improve performance and allow for greater
flexibility. Consequently, data marshalled and persisted by Infinispan
8.x is no longer compatible with Infinispan 9.x. Furthermore, as part of
our ongoing efforts to improve the cache stores provided by Infinispan,
we have removed both the JdbcBinaryStore and JdbcMixedStore in
Infinispan 9.0.

To assist users migrating from Infinispan 8.x, we have created the JDBC
Migrator that enables existing JDBC stores to be migrated to Infinispan
9's JdbcStringBasedStore.



== No More Binary Keyed Stores!


The original intention of the JdbcBinaryStore was to provide greater
flexibility over the JdbcStringBasedStore as it did not require a
Key2StringMapper implementation.  This was achieved by utilising the
hashcode of an entries key for a table's ID column entry.  However, due
to the possibility of hash collisions all entries had to be placed
inside a Bucket object which was then serialised and inserted into the
underlying table. Utilising buckets in this manner was far from optimal
as each read/write to the underlying table required an existing bucket
for a given hash to be retrieved, deserialised, updated, serialised and
then re-inserted back into the db.



== Introducing JDBC Migrator



The JDBCMigrator is a standalone application that takes a single
argument, the path to a .properties file which must contain the
configuration properties for both the source and target stores.  To use
the migrator you need the infinispan-tools-9.x.jar, as well as the jdbc
drivers required by your source and target databases, on your
classpath.

An example maven pom that launches the migrator via mvn exec:java is
presented below:





=== Migration Examples


Below are several example .properties files used for migrating various
stores, however an exhaustive list of all available properties can be
found in
the http://infinispan.org/docs/9.0.x/user_guide/user_guide.html#jdbc_migrator[Infinispan
user guide].  

*
*

*Before attempting to migrate your existing stores please ensure you
have backed up your database!*
*
*

==== 8.x JdbcBinaryStore -> 9.x JdbcStringBasedStore



The most important property to set in this example is
"source.marshaller.type=LEGACY" as this instructs the migrator to
utilise the Infinispan 8.x marshaller to unmarshall data stored in your
existing DB tables. 



If you specified custom AdvancedExternalizer implementations in your
Infinispan 8.x configuration, then it is necessary for you to specify
these in the migrator configuration and ensure that they are available
on the migrators classpath.  To Specify the AdvancedExternalizers to
load, it is necessary to define the "source.marshaller.externalizers"
property with a comma-separated list of class names. If an ID was
explicitly set for your externalizer, then it is possible to prepend the
externalizers class name with "<id>:" to ensure the IDs is respected by
the marshaller. 







==== TwoWayKey2StringMapper Migration



As well as using the JDBC Migrator to migrate from Infinispan 8.x, it is
also possible to utilise it to migrate from one DB dialect to another or
to migrate from one TwoWayKey2StringMapper implementation to another. 







=== Summary



Infinispan 9 stores are no longer compatible with Infinispan 8.x stores
due to internal marshalling changes. Furthermore, the JdbcBinary and
JdbcMixed stores have been removed due to their poor performance
characteristics.  To aid users in their transition from Infinispan 8.x
we have created the JDBC Migrator to enable users to migrate their
existing JDBC stores.

If you're a user of the JDBC stores and have any feedback on the latest
changes, let us know via the forum, issue tracker or the #infinispan
channel on Freenode. 


