---
layout: blog
title: Executing Code in the Grid
date: '2018-02-01T06:37:00.000-08:00'
author: Unknown
tags: [ " distributed executors", "streams" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1414237157030497931
blogger_orig_url: https://blog.infinispan.org/2018/02/executing-code-in-grid.html
---
Infinispan has quite a few spectacular ways of executing code in the
grid. But I bet you haven't heard or aren't really familiar with those,
which is disappointing. I hope to fix this, however, as we have added
more information to the user guide and wanted to detail that here in
this blog.

As I am sure you are aware Infinispan can be used in embedded (in your
JVM) and remote (in a standalone server). Unfortunately, this means
there are different ways of executing code based on which mode you are
in.


==== Embedded

The embedded mode has the most features available and is the easiest to
use. The appropriate section can be found
http://infinispan.org/docs/dev/user_guide/user_guide.html#executing_code_in_the_grid[here].

One question that seems to come up more than others is how a user can
perform cache operations on all data, such as remove all elements that
match a given filter. If you are curious about this one, you should
check out the
http://infinispan.org/docs/dev/user_guide/user_guide.html#examples_2[Examples]
section with the example named "*Remove specific entries"* as it details
how a user would do exactly that.

I should also point out the new
http://infinispan.org/docs/dev/user_guide/user_guide.html#cluster_executor[Cluster
Executor] section, which is similar to Streams that replaced Map Reduce,
is here to replace the old Distributed Executor. With Cluster Executor
and Distributed Streams there is a clearer distinction between executing
code on nodes (Cluster Executor) and executing code based on data
(Distributed Streams).
**

==== Server

The server is a bit more interesting and usually requires configuration
ahead of time, unlike Embedded. It can be found in this
http://infinispan.org/docs/dev/user_guide/user_guide.html#executing_code_in_the_remote_grid[section].
The benefit of the server is most of these can invoke embedded
operations internally.

Scripting is by far the easiest to use - just insert your script and
execute - but has some
https://issues.jboss.org/browse/ISPN-6173[limitations] that we haven't
been able to fix yet.

Server tasks can run pretty much any Java but require registering
classes beforehand. Unfortunately, this section still needs to be filled
in and should be added sometime in the near future. I would say, until
then, if you are interested, you can look at some tests in
https://github.com/infinispan/infinispan/tree/master/server/integration/testsuite/src/test/java/org/infinispan/server/test/task/servertask[github].


==== Takeaway

I hope this has helped users be able to find out some more information
about the various ways of executing arbitrary code for your data. If you
have any questions or need more clarification about the features
highlighted here, please don't hesitate to let us know at any of these
http://infinispan.org/community/[places].

