---
layout: blog
title: Infinispan 9.4.0.Final
date: '2018-10-08T00:34:00.000-07:00'
author: Tristan Tarrant
tags: [ " release" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-7653318797303846822
blogger_orig_url: https://blog.infinispan.org/2018/10/infinispan-940final.html
---
== Infinispan 9.4.0.Final “Infinity Minus ONE +2”

==  

=== 10 years of Infinispan

Infinispan is 10 years old this month, and what better way to celebrate
than with a brand new Final release !!!


=== What's new

Infinispan 9.4 comes with the following new features / improvements:

Segments everywhere
9.3 brought the segmented on-heap memory container. 9.4 extends this to
provide the benefits of segmentation to off-heap as well as all of the
core cache stores. Watch as your bulk operations (size, iteration,
streams) get a big performance boost !

Transcoding everywhere
To paraphrase the Grand Moff Tarkin, “The last remnants of Compatibility
Mode have been swept away”. Transcoding, i.e. the ability to
transparently convert between a number of formats across different
endpoints, is now “fully operational”.

Transactions everywhere
Hot Rod transactions now support recovery.

Hot Rod client improvements
The Hot Rod client has received many improvements:

* Client-side statistics, complete with JMX support
* Improvements to the scalability and the behaviour of near-caches
* All of the configuration can now be supplied via the properties, which
also means easier integration with other frameworks, such as Spring
Boot.

Query improvements
Many cleanups and improvements

Bugfixes, stability, reliability
Although not as exciting as new features, we continued our work to
improve the stability, reliability and performance of all aspects of
Infinispan.

Upgrades:

* As usual the latest and greatest JGroups 4.0.15
* The server is now based on WildFly 14

=== Get it, Use it, Ask us!

Please http://infinispan.org/download/[download],
https://issues.jboss.org/projects/ISPN[report bugs],
https://infinispan.zulipchat.com/[chat with us],
https://developer.jboss.org/en/infinispan/content[ask questions on the
forum] or on
https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].
