---
layout: blog
title: 10.0.0.Alpha3 and 9.4.6.Final
date: '2019-01-28T01:35:00.001-08:00'
author: Tristan Tarrant
tags: [ " release", "alpha" ]
blogger_id: tag:blogger.com,1999:blog-5717179571414330874.post-1707835156921122618
blogger_orig_url: https://blog.infinispan.org/2019/01/1000alpha3-and-946final.html
---
Hey there,

the Infinispan team has cooked two releases for you today:


== 10.0.0.Alpha3

This release contains 3 features:



* [ISPN-4075] - State transfer should preserve the creation timestamp of
entries
* [ISPN-9320] - Automatic hot rod client version selection
* [ISPN-9625] - Make clustered locks configuration possible by XML
* [ISPN-9771] - Support for configuration in JSON format

We've also started removing code which was deprecated in the past, so
check the
http://infinispan.org/docs/dev/upgrading/upgrading.html[upgrading
document] to see what you need to adapt in your application. This
document will receive further changes during the 10.0 cycle.

https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310799&version=12339174[The
complete list of issues resolved in 10.0.0.Alpha3.]

Some other features are in the works and should be landing during the
beta period. Check the
https://blog.infinispan.org/2018/11/the-road-to-infinispan-10-alpha1.html[first
of the alpha posts] to learn more about the new stuff.



== 9.4.6.Final

The stabilization of 9.4 continues with this micro release.

Highlights are:


* [ISPN-7889] - BaseDistributionInterceptor.remoteGet may cause
concurrency issues
[ISPN-8889] - Data race in NonTxInvocationContext
* [ISPN-9873] - Remove listeners when the lock is removed
* [ISPN-9822] - BasicComponentRegistryImpl fails with security manager
* [ISPN-9819] - Improve Spring-Session events handling in remote and
embedded


https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310799&version=12340282[The
complete list of issues resolved in 9.4.6.Final.]


Please report any issues in our
https://issues.jboss.org/browse/ISPN[issue tracker] and join the
conversation in our https://infinispan.zulipchat.com/[Zulip Chat] to
shape up our next release.
