---
layout: blog
title: Infinispan 10.1.0.Beta1
date: '2019-11-18T12:00:00.000-00:00'
author: Tristan Tarrant
tags: [ "beta", "release" ]
---

= Infinispan 10.1

Dear Infinispan community,

Quick on the heels of Infinispan 10.0 here comes the first Beta or 10.1.

== Server

This release closes the gap between the legacy server and the new server we introduced in 10.0. In particular:

* The reworked console (which will be described in detail in an upcoming series of blog posts)
* Kerberos authentication for both Hot Rod (GSSAPI, GS2) and HTTP/Rest (SPNEGO)
* Query and indexing operations/stats are now exposed over the RESTful API
* Tasks and Scripting support

== Non-blocking

More work has landed on the quest to completely remove blocking calls from our internals. The following have been made non-blocking:

* the size operation
* cache stream ops with primitive types

Additionally caches now have a reactive Publisher which is intended as a fully non-blocking approach to distributed operations.

== Components upgrades

* rxjava 2.2.12
* smallrye metrics 2.3.0
* microprofile metrics 2.2

== Bug fixes, clean-ups and documentation

Over 40 bug fixes. See the link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12310799&version=12343102[full list of changes and fixes]

== Get it, Use it, Ask us!

Please http://infinispan.org/download/[download],
https://issues.jboss.org/projects/ISPN[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

Infinispan 10.1.0.CR1 is scheduled for December the 7th.

