---
layout: blog
title: Infinispan Operator 1.0.1
date: '2019-11-25T12:00:00.000-00:00'
author: Vittorio Rigamonti
tags: [ "dev-preview", "release" ]
---

= Infinispan Operator 1.0.1 “Chupacabra Trainer”

Dear Infinispan community,

we know you are happy with the new shining 10.0.0 Infinispan release, but if you are among those who are missing a new operator version for safely running your Infinispan Chupachabra in the clound, this post is for you!

=== Versioning and channels
This is our first blog post about 1.0.x operator series (yeah, sorry 1.0.0 we forgot about you) and as you can notice there's no Alpha, Beta or CR label at the end of the release tag.  This is because OperatorHub and Openshift Catalog only allow numerical version like Maj.Min.Mic and instead of labels we now use the channel to indicate the stability of a release. We have 2 live channels at the moment for the Infinispan operator: `stable` and `dev-preview`. Current `stable` is 0.3.2 which is for the 9.x Infinispan cluster and current `dev-preview` is 1.0.1 which works with 10.x clusters.

=== New features
- New Infinispan image configuration: we cleaned up the image configuration process: instead of rely on a large set of env variables, now the operator configures the Infinispan image via a single .yaml file.
- Container configurability: CR .yaml file lets you configure memory and CPU (and also extras Java opts) assigned to the container;
- Encryption: TLS can be setup providing TLS certificates or using platform service as the Openshift seriving certs service (TLS will be on by default in the next release);
- We now have some good docs: https://infinispan.org/infinispan-operator/master/operator.html;
- Project README has been also improved: https://github.com/infinispan/infinispan-operator/blob/1.0.1/README.md;

=== Get it
The Infinispan Operator 1.0.1 works on Kind/Kubernetes 1.16 (CI) and Openshift 3.11, 4.x (developed on). You can install it:

- manually, follow the README;
- with OLM on Kubernetes, https://operatorhub.io/operator/infinispan/dev-preview/infinispan-operator.v1.0.0
- with OLM from the Openshift Operator Catalog

And remember: it's a dev-preview release, you can have a lot of fun with it!

=== Contribute
As usual source code is open at: https://github.com/infinispan/infinispan-operator. You can see what's going on, comment the code or the new pull requests, ask for new features and also develop them!

Thanks for following us,
Infinispan
