---
layout: blog
title: Infinispan 11.0.0.Alpha2 and 10.1.3.Final
date: '2020-03-03T12:00:00.000-00:00'
author: Tristan Tarrant
tags: [ "release" ]
---

= Infinispan 11.0.0.Alpha2 and 10.1.3.Final

Dear Infinispan community,

we've just tagged a couple of releases.

First off is the second Alpha release of what will eventually become Infinispan 11. The https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310799&version=12344572[release notes] may not be exciting, but it is mostly preparatory work for the big features we are working on: vastly improved async cross-site replication, monitoring, query improvements, the console and the CLI, and more.

We also released a micro-update to 10.1 which fixes quite a few bugs, especially in the way we handle JMX and MP metrics and further improves the documentation.

= New release naming scheme

Starting with the next development release of Infinispan 11, we will be adopting a new naming scheme. We will no longer be using the _Alpha_ and _Beta_ monikers, but we will use a progressive _Dev_ suffix to indicate that it's a development release. The next release will therefore be called 11.0.0.Dev03.

== Get it, Use it, Ask us!

Please https://infinispan.org/download/[download],
https://issues.jboss.org/projects/ISPN[report bugs],
https://infinispan.zulipchat.com/[chat with us],
ask questions on https://stackoverflow.com/questions/tagged/?tagnames=infinispan&sort=newest[StackOverflow].

