---
layout: blog
title: Infinispan Spring Boot Starter released with Spring Boot 2.2.4.RELEASE
date: '2020-02-10T12:00:00.000-00:00'
author: Katia Aresti
tags: [ "release", "spring boot", "spring" ]
---

Dear Infinispan and Spring Boot users,

We are pleased to announce the release of
https://github.com/infinispan/infinispan-spring-boot[Infinispan Spring Boot] 
*2.1.8.Final* and *2.2.0.Final*.

*2.1.8.Final* uses *Infinispan 9.4.17.Final* and *Spring Boot 2.2.2.RELEASE*

*2.2.0.Final* uses *Infinispan 10.1.1.Final* and *Spring Boot 2.2.2.RELEASE* 


== Configuring Marshalling with Infinispan 10.x

Infinispan 10.x servers have some significant changes to https://infinispan.org/docs/stable/titles/developing/developing.html#marshalling[marshalling] that impact Spring Boot users.

The default Marshaller for Infinispan 10.x is https://github.com/infinispan/protostream[ProtoStream], which uses 
https://developers.google.com/protocol-buffers[Protocol Buffers] to provide extensible, language and platform neutral
serialization.

Unfortunately ProtoStream does not currently work with Infinispan Spring Cache and Session support.
As a result, Spring users in Remote Client/Server Mode must use the https://infinispan.org/docs/stable/titles/developing/developing.html#java_serialization_marshaller[Java Serialization Marshaller] and add classes 
to a Java serialization whitelist.

Add the following configuration properties:

`infinispan.remote.marshaller=org.infinispan.commons.marshall.JavaSerializationMarshaller`
`infinispan.remote.java-serial-whitelist=org.infinispan.tutorial.simple.spring.remote.*`

The `infinispan.remote.java-serial-whitelist` property specifies the classes, or packages, that Java
serialization can marshall. Separate multiple class names with a comma (`,`).

Note that, in previous versions, JBoss Marshaller was the default for Infinispan. Spring users can also use https://infinispan.org/docs/stable/titles/developing/developing.html#jboss_marshalling[JBoss Marshalling], 
but it is deprecated as of Infinispan 10.x.

== Get it, Use it, Ask us!

You can find these releases in the maven central repository.

Please report any issues in
our https://issues.jboss.org/projects/ISPN[issue tracker] and join the
conversation in our https://infinispan.zulipchat.com/[Zulip Chat] to
shape up our next release.

Enjoy,

The Infinispan Team
