---
layout: blog
title: Infinispan 14.0.0.CR1
permalink: /blog/:year/:month/:day/infinispan-14
date: '2022-08-09T12:00:00.000-00:00'
author: ttarrant
tags: [ "release", "development" ]
---

= Infinispan 14.0.0.CR1

Dear Infinispan community,

Infinispan 14 candidate release 1 is here! Here is your chance to verify your application against our latest and greatest and tell us if things are working as expected or if there are any showstoppers we should address before tagging the final release.

== AArch64 images

We are now building images for AArch64 (aka ARM64) by default, which allow you to run Infinispan on Apple Silicon, Amazon Graviton and other ARM CPU platforms without resorting to emulation.

== Protobuf oneof support

Protostream has been updated to support ProtoBuf 3's `oneof` keyword.

== Console

When creating a new cache, it's now possible to choose the key/value types from the list of available protobuf schemas.

== CLI

The CLI can now connect to a server secured with client certificate authentication. The `config` command now supports the `keystore` and `keystore-password` to persist the client certificate configuration. Additionally, the new `config reset` command offers a quick way to reset all configuration properties to their default values.

== Release notes

You can look at the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310799&version=12391864[release notes] to see what has changed.

Get them from our https://infinispan.org/download/[download page].

