---
layout: blog
title: Infinispan 14.0.0.Dev04
permalink: /blog/:year/:month/:day/infinispan-14
date: '2022-07-14T12:00:00.000-00:00'
author: wburns
tags: [ "release", "development" ]
---

= Infinispan 14.0.0.Dev04

Dear Infinispan community,

Infinispan 14 development release 04 is here! We are nearing the final release of Infinispan 14 Final, so we want to share a preview of what's coming.

== HotRod 4.0 Protocol

With the addition of the new API that was released in the previous Dev03 build of Infinispan we have had to update the HotRod protocol to satisfy the requirements of that API.
The new protocol changes many of the operations to return additional information to include entry metadata as well as adding new header information to support the OpenTelemetry feature described below.

== OpenTelemetry

Support OpenTelemetry tracing, for tracing cache operations executed by the Infinispan server, correlated with client requests (using both Hot Rod and REST APIs).
Look out for a separate blog post describing this is in more detail later!

== Rest Endpoint

New distribution endpoint to provide exposing the data distribution information about the node and cluster. Includes node name, number of entries and total number of entries in the cluster

== RESP Server Connector

The RESP connector is now exposed by default on the single port with the other protocols. If not explicitly configured a Replicated cache is used for its cache.

== IOUring Server Compatibility

Our server can now utilize IOUring for its network socket connections. This requires a compatible Linux kernel to work properly. This can be enabled by setting the JVM property `infinispan.server.channel.iouring` to `true`.

== Command Line Interface

It is now possible to access the entry value information for data in the cache. Previously only the key information was available.

== Multimap duplicates

The Multimap API has been enhanced to now support duplicate values for a given key. This is an optional configuration as you can still allow only distinct values for a given key.
For example, your data may be `A = [1,2,3,3,5]` when duplicates are allowed.

== Size Command optimizations

Size command has received some optimizations to increase performance under certain circumstances. This includes cases of shared stores and not having expiration for data.

== Documentation

As always, the Infinispan team hope you find the documentation useful and complete. We’d love to hear from you and really value feedback from our community. If you think something is missing from the docs or spot a correction, please get in touch and we’ll get on it straight away.


== Release notes

You can look at the https://issues.redhat.com/secure/ReleaseNote.jspa?projectId=12310799&version=12388164[release notes] to see what has changed.

Get them from our https://infinispan.org/download/[download page].

